import type { SpecRow } from "./evSpecifications";

/** Parameter tables from “Other Machinery.xlsx”. */
export const otherMachinerySpecificationsByModel: Record<string, SpecRow[]> = {
  D170: [{ item: "Weight/Working devicekg", unit: "kg", parameter: "17400" }, { item: "Minimum Turning Radius", unit: "mm", parameter: "2800" }, { item: "Ground pressure", unit: "kpa", parameter: "56/51/47" }, { item: "Overall dimensions", unit: "mm", parameter: "5930×4060×3600" }, { item: "Engine Model", unit: "-", parameter: "WD10G178E25" }, { item: "Rated Power/Rated Speed", unit: "kW/rpm", parameter: "131/1850" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅱ" }],
  D170LGP: [{ item: "Weight/Working device", unit: "kg", parameter: "19400" }, { item: "Minimum Turning Radius", unit: "mm", parameter: "3200" }, { item: "Ground pressure", unit: "kpa", parameter: "26/30" }, { item: "Overall dimensions", unit: "mm", parameter: "5670×4150×3380" }, { item: "Engine Model", unit: "-", parameter: "WD10G178E25" }, { item: "Rated Power/Rated Speed", unit: "kW/rpm1", parameter: "31/1850" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅱ" }],
  "D260(EU StageⅠ)": [{ item: "Weight/Working device", unit: "kg", parameter: "23300" }, { item: "Minimum Turning Radius", unit: "mm", parameter: "4500" }, { item: "Ground pressurekpa66", unit: "kpa", parameter: "66" }, { item: "Overall dimensions", unit: "mm", parameter: "5590×3725×3527" }, { item: "Engine Model", unit: "-", parameter: "NT855-C280" }, { item: "Rated Power/Rated Speed", unit: "kW/rpm", parameter: "187/1850" }, { item: "Emission", unit: "-", parameter: "EU StageⅠ" }],
  "D360(EU StageⅠ)": [{ item: "Weight/Working device", unit: "kg", parameter: "34300" }, { item: "Minimum Turning Radius", unit: "mm", parameter: "3800" }, { item: "Ground pressure", unit: "kpa", parameter: "83/77/71" }, { item: "Overall dimensions", unit: "mm", parameter: "6550x4130x3700" }, { item: "Engine Model", unit: "-", parameter: "NTA855–C360S10" }, { item: "Rated Power/Rated Speed", unit: "kW/rpm", parameter: "257/2000" }, { item: "Emission", unit: "-", parameter: "EU StageⅠ" }],
  D5AT: [{ item: "Weight/Working device", unit: "kg", parameter: "17400" }, { item: "Minimum Turning Radius", unit: "mm", parameter: "2800" }, { item: "Ground pressure", unit: "kpa", parameter: "55/50/46" }, { item: "Overall dimensions", unit: "mm", parameter: "5580×3455×3300" }, { item: "Engine Model", unit: "-", parameter: "SC9DF270G3" }, { item: "Rated Power/Rated Speed", unit: "kW/rpm", parameter: "199/2200" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅲ" }],
  WZ30_25: [{ item: "Bucket capacity", unit: "m³", parameter: "1" }, { item: "Rated load", unit: "kg", parameter: "2500" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.3" }, { item: "Max digging depth", unit: "mm", parameter: "4440" }, { item: "Rated power", unit: "kW", parameter: "65" }, { item: "Operating weight", unit: "kg", parameter: "9500" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "8100×2310×3424" }],
  XC8_C2570: [{ item: "Bucket capacity", unit: "m³", parameter: "1.3" }, { item: "Rated load", unit: "kg", parameter: "2500" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.2" }, { item: "Max digging depth", unit: "mm", parameter: "4440" }, { item: "Rated power", unit: "kW", parameter: "73.5" }, { item: "Operating weight", unit: "kg", parameter: "7600" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "7340×2350×3437" }],
  XC8_S0750: [{ item: "Bucket capacity", unit: "m³", parameter: "0.36" }, { item: "Rated load", unit: "kg", parameter: "700" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.06" }, { item: "Max digging depth", unit: "mm", parameter: "2755" }, { item: "Rated power", unit: "kW", parameter: "45/36.8" }, { item: "Operating weight", unit: "kg", parameter: "3800" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "3760×1612×2300" }],
  XC8_S2570: [{ item: "Bucket capacity", unit: "m³", parameter: "1" }, { item: "Rated load", unit: "kg", parameter: "2500" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.2" }, { item: "Max digging depth", unit: "mm", parameter: "4351" }, { item: "Rated power", unit: "kW", parameter: "73.5" }, { item: "Operating weight", unit: "kg", parameter: "8200" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "6199×2508×3682" }],
  XC8_S3570: [{ item: "Bucket capacity", unit: "m³", parameter: "1.3" }, { item: "Rated load", unit: "kg", parameter: "3500" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.26" }, { item: "Max digging depth", unit: "mm", parameter: "5555（extended)" }, { item: "Rated power", unit: "kW", parameter: "73.5" }, { item: "Operating weight", unit: "kg", parameter: "9750" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "6137×2587×3716" }],
  XC8_S3580: [{ item: "Bucket capacity", unit: "m³", parameter: "1.3" }, { item: "Rated load", unit: "kg", parameter: "3500" }, { item: "Backhoe bucket capacity", unit: "m³", parameter: "0.26" }, { item: "Max digging depth", unit: "mm", parameter: "5555（extended)" }, { item: "Rated power", unit: "kW", parameter: "-82" }, { item: "Operating weight", unit: "kg", parameter: "10000" }, { item: "Overall machine dimensions L*W*H", unit: "mm", parameter: "6137×2510×3716" }],
  XH235L: [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated Power", unit: "kW", parameter: "194" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅲ" }, { item: "Operating Weight", unit: "kg", parameter: "24800" }, { item: "Working Width", unit: "mm", parameter: "3820" }, { item: "Dimensions", unit: "mm", parameter: "8365×3820×3850" }],
  XH285L: [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated Power", unit: "kW", parameter: "242" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅲ" }, { item: "Operating Weight", unit: "kg", parameter: "28500" }, { item: "Working Width", unit: "mm", parameter: "3820" }, { item: "Dimensions", unit: "mm", parameter: "8300×3830×3845" }],
  "XH365L(Stage Ⅲ)": [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated Power", unit: "kW", parameter: "277" }, { item: "Emission", unit: "-", parameter: "EU Stage III" }, { item: "Operating Weight", unit: "kg", parameter: "36500" }, { item: "Working Width", unit: "mm", parameter: "4000" }, { item: "Dimensions", unit: "mm", parameter: "9281×4000×3996" }],
  "XH365L(Stage Ⅴ)": [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated Power", unit: "kW", parameter: "343" }, { item: "Emission", unit: "-", parameter: "EU Stage V" }, { item: "Operating Weight", unit: "kg", parameter: "36500" }, { item: "Working Width", unit: "mm", parameter: "4000" }, { item: "Dimensions", unit: "mm", parameter: "9281×4000×3996" }],
  XZ1000E: [{ item: "Engine", unit: "-", parameter: "Weichai WP10HG313E672" }, { item: "Rated power", unit: "kW/ rpm", parameter: "230/2200" }, { item: "Max. rotation speed", unit: "r/min", parameter: "100" }, { item: "Mud pump Max. flow", unit: "L/min", parameter: "800" }, { item: "Mud pump Max. pressure", unit: "Mpa", parameter: "10" }, { item: "Drill pipe", unit: "mm×m", parameter: "114/127 (optional) x 6 m" }, { item: "Max. entry angle", unit: "°", parameter: "18" }, { item: "Max. back reaming diameter", unit: "mm", parameter: "1200" }, { item: "Weight", unit: "kg", parameter: "20t" }, { item: "Outline dimensions", unit: "mm", parameter: "10780×2850×2770" }],
  XZ230E: [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated power", unit: "kW", parameter: "115" }, { item: "Max. rotation speed", unit: "r/min", parameter: "230" }, { item: "Mud pump Max. flow", unit: "L/min", parameter: "55" }, { item: "Mud pump Max. pressure", unit: "Mpa", parameter: "10" }, { item: "Recommended  drill pipe", unit: "mm×m", parameter: "60×3" }, { item: "Max. entry angle", unit: "°", parameter: "20" }, { item: "Max. back reaming diameter", unit: "mm", parameter: "6000" }, { item: "Weight", unit: "t", parameter: "9" }, { item: "Outline dimensions", unit: "mm", parameter: "6100×2230×2450" }],
  XZ3000F: [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated power", unit: "kW", parameter: "2×264" }, { item: "Power head Max. thrust-pull force", unit: "kN", parameter: "3000" }, { item: "Power head Max. thrust-pull speed", unit: "m/min", parameter: "42" }, { item: "Power head Torque", unit: "N·m", parameter: "92" }, { item: "Power head Max. rotation speed", unit: "r/min", parameter: "95" }, { item: "Mud pump Max. flow", unit: "L/min", parameter: "Additional" }, { item: "Mud pump Max. pressure", unit: "Mpa", parameter: "10/20" }, { item: "Crane Lifting weight", unit: "t", parameter: "3.2" }, { item: "Crane Lifting moment", unit: "t•m", parameter: "6.4" }, { item: "Recommended  drill pipe", unit: "mm×m", parameter: "127/ 140×6" }, { item: "Max. entry angle", unit: "°", parameter: "16" }, { item: "Max. back reaming diameter", unit: "mm", parameter: "1500" }, { item: "Weight", unit: "t", parameter: "35" }, { item: "Outline dimensions", unit: "mm", parameter: "13700×3230×3450" }],
  XZ450E_R: [{ item: "Engine", unit: "-", parameter: "WP10HG230E670" }, { item: "Max.Torque", unit: "N ·m", parameter: "19000" }, { item: "Max.Rotation", unit: "Speedr/min", parameter: "210" }, { item: "Max.Mud Flow", unit: "L/min", parameter: "600" }, { item: "Max.Mud Pressure", unit: "MPa", parameter: "8" }, { item: "Drill Pipeφ", unit: "mm×m", parameter: "89×3000" }, { item: "Max.EntryAngle", unit: "-", parameter: "18" }, { item: "Max.Reaming Diameter", unit: "mm", parameter: "900" }, { item: "Weight", unit: "kg", parameter: "15.5" }],
  XZ5000F: [{ item: "Engine", unit: "-", parameter: "Cummins" }, { item: "Rated power", unit: "kW", parameter: "2×294" }, { item: "Power head Max. thrust-pull force", unit: "kN", parameter: "5000" }, { item: "Power head Max. thrust-pull speed", unit: "m/min", parameter: "35" }, { item: "Power head Torque", unit: "N·m", parameter: "140" }, { item: "Power head Max. rotation speed", unit: "r/min", parameter: "90" }, { item: "Mud pump Max. flow", unit: "L/min", parameter: "Additional" }, { item: "Mud pump Max. pressure", unit: "Mpa", parameter: "10" }, { item: "Crane Lifting weight", unit: "t", parameter: "3.2" }, { item: "Crane Lifting moment", unit: "t•m", parameter: "12.5" }, { item: "Recommended  drill pipe", unit: "mm×m", parameter: "φ168/φ194×9.6" }, { item: "Max. entry angle", unit: "°", parameter: "16" }, { item: "Max. back reaming diameter", unit: "mm", parameter: "Φ1600" }, { item: "Weight", unit: "t", parameter: "60" }, { item: "Outline dimensions", unit: "mm", parameter: "17500×3200×3650" }],
  XZ6000F: [{ item: "Max. Thrust-pull Force", unit: "kN", parameter: "6000" }, { item: "Max. Torque", unit: "N·m", parameter: "160000" }, { item: "Engine Power", unit: "kW", parameter: "2×354" }, { item: "Engine Model", unit: "-", parameter: "Cummins QSZ13" }, { item: "Emission standard", unit: "-", parameter: "CN III" }, { item: "Max. Thrust-pull Speed", unit: "m/min", parameter: "35" }, { item: "Max. Rotation Speed", unit: "r/min", parameter: "90" }, { item: "Max. Mud Flow", unit: "L/min", parameter: "External" }, { item: "Drill Pipe", unit: "mm×m", parameter: "168/140×9.6" }, { item: "Max. Entry Angle", unit: "°", parameter: "16" }, { item: "Max. Reaming Dia.", unit: "mm", parameter: "1800" }, { item: "Weight", unit: "t", parameter: "59" }, { item: "Dimension", unit: "L×W×H", parameter: "20000×3400×3770" }],
  XZ6600: [{ item: "Engine", unit: "-", parameter: "Volvo" }, { item: "Rated power", unit: "kW", parameter: "2×565" }, { item: "Power head Max. thrust-pull force", unit: "kN", parameter: "6600" }, { item: "Power head Max. thrust-pull speed", unit: "m/min", parameter: "32" }, { item: "Power head Torque", unit: "N·m", parameter: "180/210" }, { item: "Power head Max. rotation speed", unit: "r/min", parameter: "90" }, { item: "Mud pump Max. flow", unit: "L/min", parameter: "Additional" }, { item: "Mud pump Max. pressure", unit: "Mpa", parameter: "20" }, { item: "Crane Lifting weight", unit: "t", parameter: "5" }, { item: "Crane Lifting moment", unit: "t•m", parameter: "12.5" }, { item: "Recommended  drill pipe", unit: "mm×m", parameter: "168/194×9.6" }, { item: "Max. entry angle", unit: "°", parameter: "16" }, { item: "Max. back reaming diameter", unit: "mm", parameter: "2000" }, { item: "Weight", unit: "t", parameter: "73" }, { item: "Outline dimensions", unit: "mm", parameter: "19000×3200×3600" }],
};

/** Product description copy from the same workbook. */
export const otherMachineryDescriptionsByModel: Record<string, string> = {
  D170: "The D170 (Export) Bulldozer is a hydrodynamic transmission, electronically controlled power-shift machine engineered by XCMG specifically for international markets. Built upon XCMG’s proven product excellence, the bulldozer delivers dependable performance, operational stability, and long-term reliability across demanding job sites.\n\nDesigned for versatility, the D170 is well-suited for earthmoving, excavation, backfilling, material pushing, and transportation of soil and rock in a wide range of applications, including highways, railways, airports, river engineering, and large-scale infrastructure developments. It serves as an essential piece of equipment for national defence projects, urban development, water conservancy construction, and other critical engineering operations.",
  D170LGP: "The D170LGP Bulldozer is a hydrodynamic transmission, electronically controlled power-shift machine developed by XCMG to meet the demands of overseas markets. Designed with XCMG’s trusted engineering standards, it offers consistent performance, durability, and reliable operation in a variety of challenging working environments.\n\nEngineered for efficient earthmoving applications, the D170LGP is suitable for excavation, backfilling, material pushing, and the transportation of soil and rock across projects such as highways, railways, airports, river engineering, and large-scale site preparation. It plays a vital role in infrastructure development, including national defence projects, urban construction, water conservancy works, and other essential engineering operations.",
  "D260(EU StageⅠ)": "The D260 (Stage I) Bulldozer is a hydraulic-drive, electronically controlled power-shift machine developed by XCMG for overseas markets. Built for reliable performance and durability, it is ideal for excavation, backfilling, pushing, and transporting earth and rock in highways, railways, airports, and infrastructure projects, including urban development and water conservancy construction.",
  "D360(EU StageⅠ)": "The D360 Bulldozer is a hydraulic-drive, electronically controlled power-shift machine developed by XCMG, designed for dependable performance and durability. It is ideal for excavation, backfilling, pushing, and transporting earth and rock across highways, railways, airports, river engineering, and major infrastructure projects, including urban development and water conservancy construction.",
  D5AT: "The D5AT (Export) Bulldozer is a hydraulic-drive, electronically controlled power-shift machine developed by XCMG for international markets. Engineered to deliver dependable performance, it combines advanced technology with high reliability to ensure efficient and consistent operation across demanding construction environments.\n\nDesigned to support a wide range of infrastructure and development projects, the D5AT is an essential construction machine for national defence initiatives, urban development, water conservancy projects, and various large-scale engineering applications where durability and operational efficiency are critical.",
  WZ30_25: "Developed through XCMG’s global R&D platform, the WZ30-25 Backhoe Loader is built to meet customer needs with reliable performance, strong adaptability, and enhanced safety. Designed for easy maintenance and smooth maneuverability, it delivers efficient and cost-effective operation for various construction applications.",
  XC8_C2570: "Developed through XCMG’s global R&D platform, the XC8-C2570 Backhoe Loader is designed to meet customer needs with outstanding reliability, adaptability, safety, and ease of maintenance. It delivers strong maneuverability and cost-effective performance for various construction applications.",
  XC8_S0750: "Developed through XCMG’s global R&D platform, the XC8-S0750 Backhoe Loader is designed to deliver reliable, safe, and adaptable performance across diverse working conditions. With easy maintenance, excellent maneuverability, and cost-effective operation, it is well-suited for a wide range of construction tasks.",
  XC8_S2570: "Developed through XCMG’s global R&D platform, the XC8-S2570 Backhoe Loader is engineered to meet customer demands with exceptional reliability, safety, and environmental adaptability. Offering easy maintenance, excellent maneuverability, and cost-efficient operation, it is built for versatile construction applications.",
  XC8_S3570: "Developed through XCMG’s global R&D platform, the XC8-S3570 Backhoe Loader is engineered to meet diverse customer requirements with exceptional reliability, adaptability, safety, and ease of maintenance. It offers excellent maneuverability and cost-efficient performance for a variety of construction applications.",
  XC8_S3580: "Developed through XCMG’s global R&D platform, the XC8-S3580 Backhoe Loader is designed to meet evolving customer needs with outstanding reliability, adaptability, safety, and ease of maintenance. It delivers excellent maneuverability and cost-effective performance across a wide range of operating environments.",
  XH235L: "The XH235L Soil Compactor is designed for pushing, leveling, and compaction in large-scale foundation projects, including road bases, water conservancy dams, airports, and landfill operations. Powered by a six-cylinder water-cooled Cummins engine, it delivers reliable performance in demanding environments while complying with EU Stage III emission standards.",
  XH285L: "The XH285L Soil Compactor is designed for pushing, leveling, and compaction in large-scale foundation projects such as road construction, water conservancy dams, airports, and landfill operations. Powered by a six-cylinder water-cooled Cummins engine, it ensures dependable performance in demanding conditions while meeting EU Stage III emission standards.",
  "XH365L(Stage Ⅲ)": "The XH365 Landfill Compactor is designed for pushing and compacting solid waste in landfill sites to optimize space usage and extend landfill service life. It is also suitable for large-scale foundation projects, including road construction, water conservancy dams, airports, and other earthwork applications.",
  "XH365L(Stage Ⅴ)": "The XH285L Soil Compactor is built for pushing, leveling, and compaction in large-scale projects, including roads, dams, airports, and landfill sites. Equipped with a six-cylinder water-cooled Cummins engine, it delivers reliable performance in demanding environments and complies with EU Stage III emission standards.",
  XZ1000E: "The XZ1000E Horizontal Directional Drilling Rig is engineered for large-scale pipeline construction, delivering reliable performance in demanding drilling applications. Featuring advanced control systems and intelligent operation, it ensures enhanced safety, precision, and efficiency while optimizing fuel consumption and reducing operating costs.",
  XZ230E: "The small tonnage drilling rig is mainly used in the field of municipal pipe network construction.\nThe equipment adopts integrated design, has small size, and is flexible in construction and convenient for transportation.\nThe drilling rig can be equipped with a variety of functional components to meet diverse needs.",
  XZ3000F: "The large-tonnage drilling rig is designed for large-diameter and long-distance pipeline construction. Equipped with intelligent automation and a comprehensive digital control system, it ensures safe, efficient, and reliable operation. Its single-engine design helps improve fuel efficiency and reduce operating costs.",
  XZ450E_R: "The XZ450E-R Horizontal Directional Drilling Rig is designed for efficient large-diameter and long-distance pipeline construction. Equipped with advanced digital controls and intelligent operating systems, it delivers safe, reliable, and high-performance drilling. Its efficient power system helps optimize fuel consumption while reducing operational costs.",
  XZ5000F: "The large-tonnage drilling rig is designed for large-diameter and long-distance pipeline construction. Featuring advanced digital controls, intelligent automation, and efficient single-engine operation, it ensures safe, reliable performance while reducing fuel consumption and operating costs.",
  XZ6000F: "The large-tonnage horizontal directional drilling rig is designed for major infrastructure projects, including oil and natural gas applications. Featuring advanced intelligent systems, multiple power configurations, and internationally recognized technologies, it ensures safe, efficient, and reliable performance. The rig is equipped with a modular operating cabin and a split-type power station for enhanced flexibility and functionality.",
  XZ6600: "Large-tonnage drilling rig is mainly used for large-diameter and long-distance pipeline construction.The comprehensive digital display and adjustment of the working parameters of the equipment and the multi-directional automation and intelligent design can provide reliable guarantee for the construction safety. A single engine can be used for construction to save fuel and reduce operating costs",
};

export function otherMachinerySpecModelKey(model: string): string {
  return model.replace(/\s+/g, "").replace(/-/g, "_").replace(/\//g, "").toUpperCase();
}

export function otherMachinerySpecificationsForModel(model: string): SpecRow[] {
  const key = otherMachinerySpecModelKey(model);
  return otherMachinerySpecificationsByModel[key] ?? otherMachinerySpecificationsByModel[model] ?? [];
}

export function otherMachineryDescriptionForModel(model: string): string | undefined {
  const key = otherMachinerySpecModelKey(model);
  const d = otherMachineryDescriptionsByModel[key] ?? otherMachineryDescriptionsByModel[model];
  return d && d.trim() !== "" ? d : undefined;
}
