export type ProductEditorial = {
  summary: string;
  paragraphs: [string, string];
  benefits: [string, string, string];
  applications: [string, string, string];
  sources: string[];
  researchNote?: string;
};

const globalSource = (path: string) => `https://www.xcmgglobal.com/${path}`;
const chinaSource = (id: string) => `https://www.xcmg.com/product/pro-detail-${id}.htm`;
const brochure = (folder: string, name: string) =>
  `/brochures/catalog/Xcmg pdf/${folder}/${name}.pdf`;

function content(
  summary: string,
  performance: string,
  application: string,
  benefits: ProductEditorial["benefits"],
  applications: ProductEditorial["applications"],
  sources: string[],
  researchNote?: string,
): ProductEditorial {
  return { summary, paragraphs: [performance, application], benefits, applications, sources, researchNote };
}

/** Original editorial copy researched on 2026-10-03. Sources and variant notes
 * are retained for editors; they are not loaded into a client component.
 * Applications describe practical use cases, not guaranteed project output.
 */
export const productEditorialByModel: Record<string, ProductEditorial> = {
  LW200KV: content(
    "The XCMG LW200KV brings loading, stockpile handling and everyday site work into a compact wheel loader. It is a practical choice for teams that need useful loading capacity without the footprint of a larger machine.",
    "XCMG lists a 2,000 kg rated load and a 1.1 m³ bucket for this model. Fully hydraulic steering supports maneuvering between stockpiles and loading points, while the K-series design places emphasis on operator comfort and straightforward maintenance. Standard and high-dump working arrangements give buyers different ways to match the loader to their loading height.",
    "For construction yards, small aggregate operations and agricultural material handling, the LW200KV can support a varied daily workload. Optional pallet forks and material clamps broaden its role beyond bucket loading. Choosing the attachment around material density, truck height and available space helps turn this compact platform into a useful part of the site's material flow.",
    ["Compact platform for daily material handling", "Fully hydraulic steering for maneuvering", "Optional working equipment for different loads"],
    ["Construction yards", "Aggregate stockpiles", "Agricultural material handling"],
    [globalSource("product/compact-wheel-loader/lw200kv/")],
  ),
  ZL30E: content(
    "The XCMG ZL30E is an underground loader developed for material loading and transfer where working space is restricted. Its design addresses the confined access and demanding loading cycles encountered in mine and tunnel operations.",
    "XCMG describes a reinforced structural platform, a powertrain intended for sustained loading work and a height-adjustable cab arrangement. These features address the practical needs of underground loading: fitting within the available envelope, handling repeated loading forces and maintaining access to the working face. The machine should be selected against the actual tunnel dimensions and specified configuration.",
    "A typical role is moving excavated material between the face, a stockpile and a loading point. It can complement drilling and excavation equipment in an organized underground production cycle. For Nepal projects, access clearance, ventilation requirements and material-handling routes are useful starting points when discussing the loader with UHEEM.",
    ["Purpose-built underground loading platform", "Reinforced structure for repeated loading", "Cab arrangement suited to restricted clearance"],
    ["Underground mine loading", "Tunnel material transfer", "Confined stockpile handling"],
    [chinaSource("121138"), globalSource("product/underground-loader/zl30e/")],
  ),
  XC936: content(
    "The XCMG XC936 is a wheel loader for contractors and material-yard operators who need a balance of loading capacity, maneuverability and everyday usability. It handles recurring loading tasks without moving into the footprint of a larger loader.",
    "The global model specification pairs a 2.1 m³ bucket with a 3,500 kg rated load. XCMG's product literature emphasizes improved operator comfort, maintenance access and structural reliability. Together, those priorities support the repeated fill, travel and discharge cycles that make up a loader's working day, while giving owners a machine that is easier to inspect and service.",
    "The XC936 can support aggregate stockpiles, construction-site material movement and feeding duties around processing or batching operations. Its value comes from matching the bucket and loading arrangement to the material being handled. Assessing stockpile layout, material density and truck access helps establish where this model fits within a productive loading fleet.",
    ["Balanced capacity for recurring loading cycles", "Operator comfort for sustained daily work", "Maintenance access designed into the platform"],
    ["Aggregate yards", "Construction material handling", "Plant feeding operations"],
    [globalSource("product/wheel-loader/xc936/"), brochure("wheelloader pdf", "XC936")],
  ),
  XC938: content(
    "The XCMG XC938 is a versatile wheel loader for repeat loading and material transfer. It combines a mid-size working platform with an emphasis on operator comfort and maintainability, making it useful across construction and yard operations.",
    "XCMG's global specification lists a 3,500 kg rated load, a 1.8 m³ bucket and a 2,900 mm wheelbase. The manufacturer positions this generation around improvements in reliability, safety and service convenience. These are practical considerations for owners who need the loader to move between loading, carrying and stockpile management throughout a shift.",
    "For sand, aggregate and other bulk materials, the XC938 can form the link between storage and transport. It is a useful model to consider when a site needs more capacity than a compact loader while retaining flexibility around loading points. Bucket selection and material characteristics determine the most appropriate setup for the work.",
    ["Mid-size loading and material-transfer platform", "Comfort-focused operator environment", "Service convenience for routine maintenance"],
    ["Sand and aggregate handling", "Construction stockpiles", "Truck-loading operations"],
    [globalSource("product/wheel-loader/xc938/"), brochure("wheelloader pdf", "XC938")],
  ),
  XC958: content(
    "The XCMG XC958 steps up loading capacity for bulk-material operations. It is designed for teams handling larger stockpiles and repeated truck-loading cycles, with a working platform focused on capacity, operator comfort and serviceability.",
    "The global configuration lists a 5,500 kg rated load and a 3.2 m³ bucket, placing the XC958 above the smaller XC936 and XC938 in the catalog. Its 3,350 mm wheelbase provides a larger machine platform for material handling. XCMG highlights improvements in maintainability and comfort, which matter when the loader spends long periods working between a stockpile and waiting trucks.",
    "Aggregate processing sites, larger construction yards and bulk-material loading operations are natural applications to evaluate. The right choice depends on material density, loading height and the production rate required by the rest of the site. Matching those factors helps the XC958 contribute to a coordinated workflow rather than simply adding a larger machine.",
    ["Higher rated loading capacity", "Larger bucket for bulk-material handling", "Comfort and serviceability for repeated shifts"],
    ["Aggregate processing sites", "Bulk stockpile management", "High-volume truck loading"],
    [globalSource("product/wheel-loader/xc958/"), brochure("wheelloader pdf", "XC958")],
  ),
  XC918EV: content(
    "The XCMG XC918EV offers compact material handling with battery-electric power. It is suited to operators looking to remove diesel exhaust at the point of use while retaining the everyday loading role of a small wheel loader.",
    "The official XC918-EV specification lists a 1.0 m³ bucket, a 1,800 kg rated load and separate travel and hydraulic motor power ratings. This compact configuration is useful for smaller loading duties where a large machine is unnecessary. Electric drive changes how the loader is supplied with energy, so charging arrangements become part of the operating plan.",
    "The model can be considered for construction yards, smaller stockpile operations and routine material transfer. Its most effective deployment is on a site with a defined work cycle and access to charging. Reviewing daily loads, travel distances and charging opportunities helps establish how the XC918EV can serve the business throughout a shift.",
    ["Battery-electric loading with no diesel exhaust at use", "Compact size for smaller material-handling duties", "Separate travel and hydraulic electric drives"],
    ["Small construction yards", "Routine stockpile loading", "Local material transfer"],
    [globalSource("product/electric-wheel-loader/xc918-ev/")],
  ),
  XC938EV: content(
    "The XCMG XC938EV brings battery-electric loading to a mid-size material-handling platform. It offers a practical route to electrifying repeat yard duties, particularly where the daily workload and charging location can be planned together.",
    "The project catalog and included XC938-EV brochure identify a 3,500 kg rated load and a 2.1 m³ bucket. Separate electric drives support travel and hydraulic work. For an owner, this creates a different energy-management routine from a diesel loader while retaining the familiar tasks of filling a bucket, carrying material and loading a truck.",
    "Aggregate yards, construction support areas and batching operations can be useful applications to assess. The model is most compelling when loading routes are predictable and charging can be arranged around the shift. Material density, bucket choice and the actual duty cycle remain central to specifying a machine that fits the site.",
    ["Electric alternative for mid-size yard loading", "Useful capacity for repeat material-transfer work", "Defined work cycles support charging planning"],
    ["Aggregate yards", "Batching-plant material handling", "Construction support areas"],
    [brochure("wheelloader pdf", "XC938-EV")],
  ),
  XC968EV: content(
    "The XCMG XC968EV combines battery-electric drive with a larger loading platform for demanding material-handling work. It is a strong model to evaluate when a business wants to electrify substantial, recurring loading duties.",
    "The official XC968-EV page lists a 3.5 m³ bucket, twin 120 kW travel-motor ratings and an 80 kW hydraulic motor. The manufacturer's application examples include gravel processing and industrial material handling. This configuration supports the familiar loading cycle while replacing diesel propulsion with an electrical energy supply and a planned charging routine.",
    "For aggregate operations, industrial yards and construction-material supply, the important question is how the loader fits the production schedule. Daily material movement, travel distances and charging access should be reviewed together. A well-matched duty cycle lets buyers assess the operational benefits of electrification on their own site rather than relying on a general savings claim.",
    ["Larger bucket for bulk loading duties", "Twin electric travel-motor arrangement", "Electric drive for planned industrial workflows"],
    ["Gravel and aggregate processing", "Industrial material yards", "Construction-material loading"],
    [globalSource("product/electric-wheel-loader/xc968-ev/"), brochure("wheelloader pdf", "XC968-EV")],
  ),
  XC975EV: content(
    "The XCMG XC975EV is a battery-electric wheel loader for larger bulk-material handling tasks. Its position in the range makes it relevant to operators seeking substantial bucket capacity alongside a planned transition to electric equipment.",
    "XCMG lists a 4.5 m³ bucket, twin 120 kW travel-motor ratings and an 80 kW hydraulic motor for the XC975-EV. The larger bucket distinguishes it from smaller electric models in the catalog. That extra volume is most useful when matched to the density of the material and the loading requirements of the receiving trucks or plant.",
    "The model can be evaluated for mining-related stockpiles, major construction-material yards and industrial bulk handling. Electrification also makes charging access and shift planning part of the purchase decision. Reviewing throughput requirements and work routes helps establish whether the XC975EV is the right step up in capacity for a particular operation.",
    ["Large bucket for bulk-material workloads", "Battery-electric propulsion and hydraulic drive", "Capacity suited to planned production loading"],
    ["Bulk construction materials", "Industrial stockpiles", "Mining-related material handling"],
    [globalSource("product/electric-wheel-loader/xc975-ev/")],
  ),
  XE140I_K: content(
    "The XCMG XE140I_K is a crawler excavator for earthwork, utility construction and material handling. Its reinforced working equipment and coordinated hydraulic system give contractors a versatile platform for jobs that demand both digging ability and controlled movement.",
    "The included XE140I-K manufacturer brochure describes a turbocharged Cummins engine, reinforced boom and arm details, forged components at key hinge points and hydraulic flow matched to the workload. The operator environment includes an adjustable seat, air conditioning and a monitor. These features address the practical demands of repeat digging, positioning and loading over a working day.",
    "Typical applications include municipal earthwork, irrigation channels, building foundations and highway or bridge support work. The brochure lists different bucket arrangements, so the tool should be selected around soil conditions and material handling requirements. For a contractor with varied projects, that application match is more useful than choosing by machine size alone.",
    ["Reinforced working equipment for daily excavation", "Hydraulic flow matched to changing loads", "Operator environment designed for sustained work"],
    ["Municipal and utility earthwork", "Irrigation and drainage", "Building and road construction"],
    [brochure("Excavator", "XE 140I-K")],
  ),
  XE215I_K: content(
    "The XCMG XE215I_K is a crawler excavator for contractors undertaking sustained earthwork and loading duties. It combines reinforced working equipment with hydraulic control intended to keep digging, swing and positioning movements coordinated through changing loads.",
    "The XE215I-K brochure describes a Cummins power system, a longer undercarriage with nine supporting rollers and reinforced details around high-stress areas of the boom and arm. Its hydraulic control includes regeneration and holding functions for the working equipment. The cab brings together an adjustable seat, air conditioning and operating information for the person managing the excavation cycle.",
    "The machine can support foundation excavation, municipal construction, irrigation and highway or bridge earthwork. Different bucket and arm configurations allow the work package to be considered around reach, material type and loading demands. That makes the XE215I_K a useful candidate for businesses that need one excavator to move between several substantial construction roles.",
    ["Reinforced boom and arm construction", "Longer undercarriage with nine supporting rollers", "Hydraulic functions for coordinated digging cycles"],
    ["Foundation excavation", "Municipal infrastructure", "Highway and bridge earthwork"],
    [brochure("Excavator", "XE 215 I-K")],
  ),
  XE230CLC: content(
    "The XCMG XE230CLC is a crawler excavator developed for demanding digging and material-loading work. Its extended chassis and reinforced working arrangement make it a model to consider for excavation operations where repeated loading cycles are central to production.",
    "The included XE230CLC brochure describes the machine as a mining-oriented product with an extended chassis and nine rollers. It presents a heavy-duty bucket arrangement and hydraulic digging capabilities for earth and rock work. Those design priorities are relevant when a machine must dig, swing and load consistently while working alongside trucks or processing equipment.",
    "For quarry material handling, bulk earthwork and larger construction excavations, the XE230CLC should be matched to the ground conditions and required loading reach. A suitable bucket and arm arrangement can help align the machine with the rest of the site. Truck access and the loading sequence are also important when evaluating its role in a production fleet.",
    ["Extended chassis for the excavation platform", "Heavy-duty working arrangement", "Designed around repeated digging and loading"],
    ["Quarry material handling", "Bulk earthwork", "Larger construction excavations"],
    [brochure("Excavator", "XE 230CLC")],
  ),
  XE380C: content(
    "The XCMG XE380C is a larger crawler excavator for substantial earthmoving and truck-loading tasks. It is aimed at operations where the scale of the excavation calls for a heavier machine platform and a carefully matched working arrangement.",
    "The included XE380C brochure identifies a 36,600 kg operating weight and presents the model loading excavated material into a haul truck. This places it in a different working class from the smaller excavators in the catalog. Its selection should focus on the required bucket, reach and loading geometry, with the final configuration matched to the material being excavated.",
    "Bulk excavation, quarry support and major infrastructure earthwork are useful roles to assess. A larger excavator contributes most when loading capacity is coordinated with truck availability and site access. Reviewing those factors with UHEEM helps establish whether the XE380C fits the production task and the practical constraints of moving and operating it on the project.",
    ["Larger platform for substantial excavation", "Suited to organized truck-loading workflows", "Working arrangement selected around material and reach"],
    ["Bulk excavation", "Quarry support", "Major infrastructure earthwork"],
    [brochure("Excavator", "XE 380C ")],
    "Brochure cover identifies Isuzu and a 1.5–1.8 m³ bucket; legacy parameter table differs. Numeric engine/bucket claims are excluded from prose pending configuration review.",
  ),
  XE215EV: content(
    "The XCMG XE215EV brings battery-electric power to full-size excavation and loading work. It offers contractors a way to remove diesel exhaust at the machine while keeping the working functions needed for urban construction and industrial earthmoving.",
    "XCMG describes a lithium iron phosphate battery, IP67 protection for key electrical components and a permanent-magnet synchronous motor. Multiple attachment-control modes, automatic lubrication and a touch-screen display support daily operation. A reinforced upper structure and optimized boom and arm address the repeated mechanical demands of digging and material handling.",
    "The official applications include urban construction, mines, cargo yards and tunnel projects. On any electric-excavator deployment, charging access and daily duty cycles deserve the same attention as bucket selection and working reach. Reviewing these together helps buyers determine how the XE215EV can fit an actual project schedule.",
    ["Battery-electric excavation at the point of use", "Protected key electrical components", "Attachment modes and automatic lubrication"],
    ["Urban construction", "Industrial cargo-yard work", "Tunnel and mine projects"],
    [globalSource("product/electric-excavator/xe215ev/")],
  ),
  RP905HEV: content(
    "The XCMG RP905HEV is a hybrid paver built around controlled material delivery and consistent paving movement. It combines range-extender power with battery support for contractors assessing new-energy equipment within a complete road-construction workflow.",
    "The official description identifies a range extender and power battery, ultrasonic material-level sensing and electronic automatic leveling. Independently driven left and right travel systems work with automatic constant-speed control. The electrically heated hydraulic telescopic screed provides width adjustment, with hydraulic height and crown adjustments supporting the required paving profile.",
    "The specification lists a basic paving width of 3–6 m and a maximum width of 9 m. These capabilities make the RP905HEV relevant to road construction and wider paving work when matched to the screed configuration. Material supply, paving speed and the compaction sequence should be planned together to maintain an uninterrupted laying operation.",
    ["Hybrid power with range-extender support", "Automatic leveling and material-level sensing", "Telescopic screed with profile adjustments"],
    ["Road construction", "Urban road renewal", "Wider paving operations"],
    [globalSource("product/new-energy-paver/rp905hev/")],
  ),
  XCR40_EV: content(
    "The XCMG XCR40_EV is a new-energy rough-terrain crane for fixed-site lifting and material placement. XCMG positions it for construction and industrial environments where local emissions and noise are important considerations in equipment selection.",
    "The official model specification lists a 40-ton maximum lifting capacity, a 35 m telescopic boom and a two-axle chassis with 4×4×4 drive and steering. This arrangement supports repositioning within the working site. Actual lifting capacity depends on radius, boom configuration and the applicable load chart, which should guide each planned lift.",
    "The manufacturer's stated applications include construction sites, ports, docks and industrial or mining enterprises. It also identifies settings with higher noise and emissions requirements. For project planning, the useful comparison is between the required lifting geometry, ground conditions and site energy arrangements, rather than maximum capacity alone.",
    ["New-energy option for fixed-site lifting", "Rough-terrain drive and steering arrangement", "Telescopic boom for varied placement tasks"],
    ["Industrial facilities", "Construction-site lifting", "Ports and dock operations"],
    [globalSource("product/rough-terrain-crane/xcr40_ev/")],
    "Official page confirms new-energy application but not hybrid propulsion. Prose avoids the legacy Hybrid Electric label; power-system configuration requires confirmation.",
  ),
  XS265HEV: content(
    "The XCMG XS265HEV is a heavy vibratory roller for foundation layers and engineered fill. Its range-extender hybrid system makes it a relevant option for contractors evaluating new-energy machinery for demanding compaction work.",
    "XCMG identifies a 26,000 kg operating weight and a hybrid layout with motors driving the drum and rear axle. The manufacturer's description emphasizes responsive direct drive and traction for compaction operations. The specified vibration settings provide different working conditions for the material and layer being compacted, rather than a single fixed approach to every fill.",
    "The official applications include highways, airports, ports, dams and industrial construction. On these projects, the roller's role is to help prepare the foundation for the next construction stage. Material type, moisture, layer thickness and the agreed rolling pattern should be considered together when choosing and operating the XS265HEV.",
    ["Heavy platform for foundation compaction", "Range-extender hybrid drive", "Direct drive to drum and rear axle"],
    ["Highway foundation layers", "Dam and airport fill", "Industrial site preparation"],
    ["https://www.xcmg.com/product/pro-detail.jsp?id=138181"],
  ),
  GR150: content(
    "The XCMG GR150 is a motor grader for shaping surfaces and preparing the ground for the next stage of construction. It supports the detailed leveling and trimming work that turns rough earthwork into an organized road or site platform.",
    "The project brochure identifies the GR150 motor grader and its Cummins power system. A grader's working role is different from bulk excavation: the blade is used to shape the surface, establish levels and redistribute material across the work area. That makes the GR150 useful to assess when accurate finishing and maintenance are recurring parts of the contractor's workload.",
    "Road formation, shoulder maintenance, drainage shaping and site leveling are practical applications for the model. The best setup depends on the finish required, the material on site and the available working width. Coordinating grading with material placement and subsequent compaction helps the machine contribute to a consistent construction sequence.",
    ["Blade-based control for surface shaping", "Useful for grading and maintenance workloads", "Supports preparation ahead of compaction"],
    ["Road formation and shoulders", "Site leveling", "Drainage and slope shaping"],
    [brochure("motor grader", "XCMG GR150")],
    "GR150 PDF contains encoded text; model identity verified, quantitative feature claims intentionally omitted.",
  ),
  GR165: content(
    "The XCMG GR165 is a motor grader for road shaping, surface finishing and broader site preparation. It brings grading and trimming capability to contractors who need to maintain working levels across highways, access roads and infrastructure projects.",
    "The included brochure describes articulated steering, a balanced rear suspension and a self-locking differential intended to support traction. These features complement the blade's working role by helping the machine maneuver and maintain contact with the surface. The brochure also highlights cab comfort and access through the engine hood for maintenance.",
    "Ground leveling, ditch formation, slope shaping and scarifying are among the stated operations. For Nepal road projects, the GR165 can be considered as part of the sequence between bulk earthwork and final compaction. Blade setup, surface material and the required profile should be reviewed together to establish the right approach for the job.",
    ["Articulated steering for maneuvering", "Balanced rear suspension and traction support", "Cab comfort and maintenance access"],
    ["Road grading", "Ditch and slope shaping", "Infrastructure site preparation"],
    [brochure("motor grader", "XCMG GR165")],
  ),
  XP163: content(
    "The XCMG XP163 is a pneumatic-tire roller for asphalt, base layers and fill compaction. Its tire-based kneading action gives road contractors a different compaction method to evaluate alongside steel-drum equipment in the paving sequence.",
    "XCMG describes the XP163 as a self-propelled static roller with a 16,000 kg operating weight. Pneumatic tires apply a kneading action to the surface, making the machine relevant to pavement and foundation-layer operations. The model's working role should be assessed against the material, the desired finish and the compaction method specified for the project.",
    "The official applications include roads, airports, ports and dams, with particular emphasis on highway pavement. For asphalt work, the roller needs to fit the laying temperature and rolling pattern established by the construction team. For base and fill work, moisture and layer thickness are useful factors to consider when evaluating the XP163's place in the fleet.",
    ["Pneumatic-tire kneading action", "Static rolling for pavement and base layers", "Complements the wider compaction sequence"],
    ["Asphalt pavement", "Road base and subbase", "Airport and infrastructure fill"],
    [globalSource("product/pneumatic-roller/xp163/"), brochure("pneumatic roller", "XP163")],
  ),
  SQS125TL_4: content(
    "The XCMG SQS125TL_4 combines lifting equipment with a transport vehicle, helping a delivery team load, move and place materials as one coordinated operation. It is a useful solution for jobs where a separate crane would complicate the delivery sequence.",
    "The included SQS125TL-4 brochure describes a four-section telescopic boom, continuous slewing and hydraulic outriggers. These functions allow the lifting position to be arranged around the delivery point. The crane's usefulness comes from matching its working radius and installation to the load, with the applicable chart determining the lifting capacity at each position.",
    "Construction supplies, machinery deliveries and yard loading are practical applications to assess. A truck-mounted crane can help reduce the number of separate handling steps when materials need to be placed near their point of use. Chassis choice, payload after installation and access to the delivery location are important parts of specifying the complete vehicle.",
    ["Lifting and transport in one vehicle", "Telescopic reach for material placement", "Hydraulic outriggers for the lifting setup"],
    ["Construction-material deliveries", "Equipment transport", "Yard loading and unloading"],
    [brochure("truck mounted crane", "XCMG Truck mounted crane 5 ton")],
  ),
  SQS68TL_5: content(
    "The XCMG SQS68TL_5 is listed in the Nepal catalog as a truck-mounted crane for lifting and material deliveries. Its role is to bring handling capability with the transport vehicle, helping crews move a load through fewer separate stages.",
    "A truck-mounted crane is most useful when the delivery vehicle can reach the unloading area and establish the required lifting setup. The telescopic lifting arrangement should be selected against the load's dimensions, placement position and working radius. Vehicle payload and crane capacity are different considerations, so both belong in the specification of the complete transport solution.",
    "The model can be considered for supply deliveries, equipment handling and loading around construction yards. It is particularly relevant when materials need to be positioned close to where they will be used. UHEEM can help review the intended chassis and lifting task so the supplied configuration matches the delivery routes and site requirements.",
    ["Handling equipment travels with the delivery vehicle", "Useful for delivery and placement workflows", "Installation matched to chassis and load requirements"],
    ["Site supply deliveries", "Equipment handling", "Construction-yard loading"],
    [brochure("truck mounted crane", "SQS68TL-4 ")],
    "Only SQS68TL-4 brochure is supplied; SQS68TL_5 identity remains unverified. Copy is limited to catalog category and general selection context; no -4 capacity, section count or features are attributed to -5.",
  ),
  XCT25L4_Y: content(
    "The XCMG XCT25L4_Y is a truck crane for everyday construction lifting and industrial material placement. It combines road-going mobility with a telescopic lifting arrangement, making it relevant to contractors whose crane moves between different project locations.",
    "The official product page lists a 25-ton maximum capacity, a 33.5 m telescopic boom and three axles. This gives the model a useful place in general lifting work without moving into the larger crane classes. The maximum rating is a selection reference; each actual lift depends on the load chart, working radius and the specified setup.",
    "XCMG identifies logistics, warehousing and construction sites among its applications. The crane can be assessed for material placement, unloading and installation work where access and lifting geometry are well defined. Reviewing the complete lift path and setup area helps buyers match the XCT25L4_Y to the jobs they expect it to undertake.",
    ["Mobile platform for changing project locations", "Telescopic boom for general placement work", "25-ton class for everyday construction lifting"],
    ["Construction material placement", "Warehousing and logistics", "Equipment installation"],
    [globalSource("product/truck-crane/xct25l4_y/")],
  ),
  XCT25_Y1: content(
    "The XCMG XCT25_Y1 is a three-axle truck crane for versatile lifting and installation duties. Its telescopic boom and jib arrangement make it a model to consider when a contractor needs reach as well as mobility between sites.",
    "XCMG specifies a 25-ton maximum capacity, a four-section 33.5 m boom and an 8.15 m fixed jib. The combination allows different lifting geometries to be evaluated against the task. Reach and lifting capacity must be considered together, since extending the boom or using the jib changes the allowable load shown in the manufacturer's charts.",
    "The XCT25_Y1 can support planned unloading, construction-material placement and equipment installation. It is useful to assess where the crane must travel between jobs but still work from a prepared lifting position. Load dimensions, working radius and access to the setup area provide a clear basis for choosing the required boom and jib configuration.",
    ["Three-axle mobile crane platform", "Four-section telescopic boom", "Fixed jib option for additional lifting geometry"],
    ["Planned construction lifts", "Material unloading", "Equipment installation"],
    [globalSource("product/pro-detail-1193609.htm")],
  ),
  XCT50_Y1: content(
    "The XCMG XCT50_Y1 is a truck crane for contractors moving into heavier construction and installation work. It offers a larger lifting class while retaining a mobile platform that can be scheduled across different project locations.",
    "The included manufacturer brochure identifies a 50-ton maximum rating and a 45 m main boom. It describes a high-strength chassis frame and gives separate boom and jib combinations with detailed lifting charts. That information allows the crane to be assessed around the actual load position, rather than treating its headline tonnage as the capacity available at every reach.",
    "The model can be considered for structural placement, equipment installation and general infrastructure lifting. Its value depends on fitting the lifting envelope to the recurring jobs in the owner's portfolio. Transport access, counterweight arrangements and the setup space should be reviewed alongside the load chart when specifying the XCT50_Y1 for a project.",
    ["50-ton class for larger construction tasks", "45 m main-boom arrangement", "Detailed configurations for lift planning"],
    ["Structural material placement", "Industrial equipment installation", "Infrastructure lifting"],
    [brochure("truck crane", "XCT50_Y1")],
  ),
  XCT80_Y1: content(
    "The XCMG XCT80_Y1 is a four-axle truck crane for substantial infrastructure and industrial lifting. It gives operators a higher-capacity mobile option when project requirements call for a wider lifting envelope than smaller truck cranes can offer.",
    "The official product page lists an 80-ton maximum capacity and a 50.5 m telescopic boom. The manufacturer's application range spans construction, bridges, ports, power and water-conservancy facilities. This breadth makes the model useful to evaluate for a contractor with varied lifting work, provided each lift is matched to its actual configuration and load chart.",
    "Typical tasks include placing larger construction components and supporting industrial installation. The selection process should consider load weight and dimensions together with radius, boom length and the available setup area. With those requirements defined, the XCT80_Y1 can be assessed as part of a planned lifting fleet rather than selected on maximum tonnage alone.",
    ["Higher-capacity four-axle platform", "Long telescopic boom for varied lift positions", "Broad infrastructure and industrial applications"],
    ["Bridge and infrastructure work", "Industrial installation", "Port and construction lifting"],
    [globalSource("product/truck-crane/xct80_y1/"), brochure("truck crane", "XCT80_Y1")],
  ),
  XCT110_Y1: content(
    "The XCMG XCT110_Y1 is listed in the Nepal catalog for heavy construction and industrial lifting. It is a model to evaluate when the project needs a larger crane class and a mobile solution for substantial installation tasks.",
    "For work at this scale, the useful specification is the complete lifting configuration: boom and jib arrangement, counterweight, outrigger position and the load chart applicable to the supplied crane. These details determine whether the machine can reach and place the required component. They also help establish the transport and setup requirements before the crane arrives on site.",
    "Potential roles include infrastructure component placement, industrial equipment erection and larger construction lifts. Defining the recurring lift cases with UHEEM helps select the appropriate configuration and supporting equipment. That approach gives an owner a clearer view of where the XCT110_Y1 belongs in the fleet and which projects it is intended to support.",
    ["Larger crane class for substantial lift requirements", "Mobile option for installation projects", "Configuration selected around the required lift cases"],
    ["Industrial equipment erection", "Infrastructure component placement", "Large construction lifts"],
    ["src/app/_data/roadEarthSpecifications.ts"],
    "Catalog uses XCT110_Y1; legacy data substitutes XCT110_Y. Exact public manufacturer source not confirmed. No _Y boom, axle or capacity specifications are promoted as _Y1 claims.",
  ),
  XTR4260: content(
    "The XCMG XTR4/260 is a roadheader for mechanical tunnel excavation. It gives tunneling teams a machine-based cutting and loading approach to assess where the tunnel profile and ground conditions suit roadheader construction.",
    "The official specification identifies an 80-ton machine with a cutting range of 4,520 mm in height and 4,970 mm in width. It also lists a star-wheel loading arrangement and a water-spray system. These functions connect excavation at the face with the movement of cut material, helping the equipment fit within an organized tunneling sequence.",
    "The XTR4/260 can be evaluated for tunnel sections that fall within its working envelope. Selection depends on the geology, required profile and the arrangement for removing excavated material behind the machine. Power supply, ventilation and access should be considered as part of the excavation method, so the roadheader is matched to the project rather than chosen by motor power alone.",
    ["Mechanical cutting for suitable tunnel profiles", "Integrated cut-material loading arrangement", "Defined working envelope for tunnel planning"],
    ["Tunnel excavation", "Underground passage construction", "Profile-controlled mechanical cutting"],
    [globalSource("product/pro-detail-1193292.htm")],
  ),
  XTR6280: content(
    "The XCMG XTR6/280 is a roadheader for larger tunnel excavation within the XTR range. Its cutting, loading and dust-control functions are designed to work together at the face, supporting a coordinated mechanical excavation method.",
    "XCMG's model page describes a conical cutting head, a wear-resistant loading system and water spray used with onboard dust-control equipment. It also identifies remote-control capability and hydraulic control technologies. These features address the repeated cutting and material-removal tasks that determine how a roadheader fits into the tunnel's daily construction sequence.",
    "For transport tunnels and other underground works, the XTR6/280 should be selected around the required section, geology and spoil-removal route. Its value is in matching the machine's working envelope to the planned excavation method. Support installation, services behind the machine and access for maintenance are also part of an effective tunneling layout.",
    ["Cutting and loading functions at the working face", "Wear-resistant material-handling surfaces", "Spray and onboard dust-control arrangement"],
    ["Transport tunnel excavation", "Underground infrastructure", "Mechanical face excavation"],
    [chinaSource("135645")],
  ),
  XTR7360: content(
    "The XCMG XTR7/360 is a roadheader for substantial tunnel excavation. It is a candidate for projects that need a larger mechanical cutting platform and a planned workflow for excavation, material removal and installation of tunnel support.",
    "XCMG documents the model within its XTR tunneling range and in tunnel-construction applications. The machine's role is to cut the required profile and move excavated material into the removal system behind it. That makes its working envelope and compatibility with the site's support and transport arrangements central to selection.",
    "Larger transport tunnels and underground infrastructure works are useful applications to assess. The best fit depends on geology and the tunnel section, rather than the model's size alone. Establishing the cutting method, service provision and spoil-removal sequence helps the project team determine how the XTR7/360 can contribute to the planned advance at the face.",
    ["Larger platform within the XTR tunnel range", "Mechanical excavation aligned with the tunnel profile", "Integrates with planned spoil-removal operations"],
    ["Larger transport tunnels", "Underground infrastructure", "Mechanical tunneling projects"],
    [chinaSource("132799"), "https://www.xcmg.com/case/case-detail-11241898.htm"],
  ),
  XUD135: content(
    "The XCMG XUD135 is a face-drilling rig for underground excavation and mine development. It supports the drilling stage of the construction cycle, placing blast and anchor holes before excavation and support work proceed.",
    "The official description covers metal and non-metal mines, hydropower projects and smaller tunnels. It highlights a single-layer hose reel and separate impact and auxiliary pumps. Those details address the working demands of repeated drilling and equipment servicing, while the boom and feed arrangement determine how the rig reaches the planned hole positions.",
    "For mine headings and tunnel works, the XUD135 should be assessed against the face dimensions, hole pattern and required drilling depth. Access, water supply and the working services also need to fit the excavation cycle. With those requirements defined, the rig can be matched to a clear drilling task within the underground fleet.",
    ["Face drilling for blast and anchor holes", "Single-layer hose reel arrangement", "Separate impact and auxiliary pump systems"],
    ["Underground mine development", "Small tunnel excavation", "Hydropower underground works"],
    [globalSource("product/face-drill-rig/xud135/")],
  ),
  XUD275: content(
    "The XCMG XUD275 is listed as a drill jumbo for underground construction. Its role is to support planned rock-drilling work at the face, helping excavation teams coordinate drilling with the material-removal and support stages that follow.",
    "A drilling jumbo should be matched to the tunnel section, the hole pattern and the drilling method. Boom reach, feed length and the specified rock-drill arrangement determine how the working face can be covered. These are the useful points to review when choosing an underground drilling platform, rather than relying on a general description of drilling power.",
    "Mine development and tunnel construction are practical applications to discuss for this catalog entry. Site access and the provision of drilling services need to be considered alongside the work pattern. UHEEM can help review the supplied model designation and configuration so the equipment is matched to the intended underground task.",
    ["Dedicated platform for underground drilling tasks", "Selection based on face coverage and hole pattern", "Configuration matched to the excavation method"],
    ["Mine-development drilling", "Tunnel-face drilling", "Underground construction"],
    ["src/app/_data/roadEarthSpecifications.ts"],
    "Legacy data contains XTD275 and XUD275 with duplicated text. Exact XUD275 identity not independently confirmed; no XTD features or numeric claims are transferred.",
  ),
  XUD295: content(
    "The XCMG XUD295 is listed in the Nepal range as a drill jumbo for underground projects. It is intended to be evaluated around the drilling work package, from the required face coverage to the sequence of excavation and support operations.",
    "The practical requirements of a jumbo include reaching the planned drilling positions, maintaining the specified hole direction and working within the available tunnel space. Matching the machine's configuration to those requirements helps establish its role in the construction cycle. The drilling system and services should be specified together with the project team.",
    "For larger underground headings and tunnel works, defining the hole pattern and drilling depth provides a useful starting point. Access dimensions and service connections are equally relevant to the selection. UHEEM can review the catalog designation and the manufacturer's supplied configuration before matching the XUD295 to the project's drilling method.",
    ["Underground drilling platform in the Nepal catalog", "Work package defined around required face coverage", "Selection coordinated with excavation and support"],
    ["Underground headings", "Tunnel drilling", "Mine-construction drilling"],
    [globalSource("product/drill-jumbo/xtd295/"), "src/app/_data/roadEarthSpecifications.ts"],
    "Official page and local brochure identify XTD295, while catalog says XUD295. XTD295 two-boom and capacity claims are excluded until the designation is confirmed.",
  ),
  XR138E: content(
    "The XCMG XR138E is a rotary drilling rig for foundation work where the working footprint and site access matter. It is a model to consider for civil construction and smaller foundation packages within an organized piling operation.",
    "XCMG's regional description positions the XR138E family for industrial and civil foundations, including smaller building and power-tower projects. The rotary drilling platform should be configured around the required pile diameter and depth. The Kelly bar and drilling tool arrangement are important parts of that selection because they connect the machine's working capability to the ground being drilled.",
    "For urban building sites and utility foundations, the rig's role is to establish the bore required by the foundation design. Ground conditions, access for supporting equipment and the spoil-handling sequence should be reviewed together. This gives a contractor a practical basis for evaluating the XR138E without assuming that every regional configuration has identical capabilities.",
    ["Foundation platform for civil-construction work", "Working equipment selected around pile requirements", "Relevant where access and footprint matter"],
    ["Building foundations", "Utility-tower foundations", "Urban piling work"],
    ["https://www.xcmgmena.com/ar/product/rotary-drilling-rig/xr138e-euro5/"],
    "Regional source is Euro V; only family application positioning used. Nepal engine, depth and emission configuration not inferred.",
  ),
  XR158E: content(
    "The XCMG XR158E is a rotary drilling rig for contractors undertaking bored-pile foundation work. It offers a defined drilling platform that can be evaluated around pile dimensions, site conditions and the production sequence required by the foundation design.",
    "The official specification lists a maximum drilling diameter of 1,500 mm and depth configurations of 44/56 m. It also identifies a 160 kN main-winch lifting force. These figures describe the available configuration envelope; the actual bore achievable on a project depends on the selected working equipment and the conditions encountered below ground.",
    "Building foundations, bridge-support foundations and general civil piling are useful applications to assess. Choosing the drilling tools and Kelly bar around the ground investigation helps match the rig to the work. The site layout should also provide for spoil removal and the next foundation stage, allowing the XR158E to fit a coordinated construction operation.",
    ["Defined bored-pile drilling envelope", "Working equipment matched to the ground investigation", "Platform for coordinated foundation construction"],
    ["Building piles", "Bridge-support foundations", "Civil foundation construction"],
    [globalSource("product/pro-detail-1193599.htm")],
  ),
  XR178E: content(
    "The XCMG XR178E is a rotary drilling rig for civil foundations and utility piling. It combines a capable rotary drive with a dedicated crawler platform, helping contractors assess a machine around both drilling requirements and site logistics.",
    "The included South Asia brochure describes a 178 kN·m rotary drive, hydraulic mast-verticality adjustment and a rig-specific crawler chassis. It also highlights accessible maintenance points and a transport arrangement that can retain the Kelly bar. These features connect the machine's drilling role with practical issues such as setup, movement between jobs and daily servicing.",
    "The stated applications include civil engineering, municipal projects and power-grid piles, particularly in soil and sand layers. Tool selection remains important when ground conditions change. Reviewing the bore design, ground investigation and transport route gives a contractor a clear way to decide whether the XR178E fits the intended foundation package.",
    ["178 kN·m rotary drive", "Mast-verticality adjustment for setup", "Transport and maintenance arrangements for site work"],
    ["Civil foundation works", "Municipal piling", "Power-grid foundations"],
    [brochure("piling machinery", "South Asia piling rig catalog")],
  ),
  XR210I: content(
    "The XCMG XR210I is a rotary drilling rig for civil, municipal and power-grid foundation projects. It is a useful option to assess when the piling work calls for a substantial drilling platform with working equipment matched to the bore design.",
    "XCMG India's official page identifies a 210 kN·m rated output torque and positions the model for soil and sand layers. The platform's role is to combine rotary drilling with the crowd and winch functions needed for the chosen tool arrangement. Matching those functions to the required pile dimensions gives a more useful comparison than torque alone.",
    "Building piles, infrastructure foundations and utility-tower work are practical roles for the XR210I. The ground investigation and construction method should guide Kelly-bar and tool selection. Access for the rig, spoil handling and the subsequent pile-construction stages also matter when organizing an efficient foundation site.",
    ["210 kN·m rated rotary output", "Positioned for soil and sand-layer foundations", "Configuration matched to the piling method"],
    ["Civil building foundations", "Municipal infrastructure piles", "Power-grid foundation work"],
    ["https://www.xcmgindia.com/product-details.php/44"],
  ),
  XR240E: content(
    "The XCMG XR240E is a multifunctional rotary drilling rig for more demanding foundation packages. It gives contractors a platform with adaptable crowd arrangements and control functions that support setup and repeated drilling operations.",
    "XCMG describes switching between crowd-cylinder and crowd-winch functions, a 240 kN·m rotary drive and an electronically controlled turbocharged engine. Single-row rope technology is used on the main and auxiliary winches, while the control system includes mast-perpendicularity adjustment. These features address both the drilling task and the equipment-management needs of a busy foundation site.",
    "Larger building foundations, infrastructure piles and projects requiring different drilling arrangements are useful applications to evaluate. The machine should be specified against the ground investigation and chosen construction method. Defining tools, working envelope and transport arrangements together helps the XR240E support the project as a complete foundation solution.",
    ["Adaptable crowd-cylinder and crowd-winch functions", "240 kN·m rotary drive", "Mast-perpendicularity adjustment and winch technology"],
    ["Larger building foundations", "Infrastructure piling", "Varied foundation work packages"],
    [globalSource("product/rotary-drilling-rig/xr240e/")],
  ),
  SLM4: content(
    "The XCMG SLM4 is a self-loading concrete mixer for projects that need concrete prepared close to the work. It combines material handling and mixing in one mobile unit, making it relevant where deliveries from a distant batching plant are difficult to coordinate.",
    "XCMG describes five integrated functions: loading, metering, mixing, transporting and unloading. The official specification lists a 4 m³ mixing quantity, a 700 L loading bucket and a drum rotation angle of 270 degrees. This arrangement allows the machine to support the movement of ingredients and mixed concrete within the site, reducing the need to organize each stage around separate equipment.",
    "The stated applications include roads, railway works, retaining structures, dams and drainage projects, especially in remote locations. Its practical value comes from local production and placement flexibility. Mix design, material supply and quality-control arrangements should still be planned by the construction team so the SLM4 fits the concrete work package.",
    ["Loading, metering and mixing in one unit", "Mobile transport and discharge of concrete", "Useful where batching-plant access is limited"],
    ["Remote road construction", "Drainage and retaining works", "Water-conservancy projects"],
    [globalSource("product/self-loading-concrete-mixer/slm4/")],
  ),
  XS3017S: content(
    "The XCMG XS3017S is a truck-mounted concrete spraying machine for placing sprayed concrete over a wide working area. It helps crews assess mechanized spraying where reach, positioning and a coordinated supply of concrete are central to the job.",
    "The official specification lists a maximum theoretical spraying capacity of 30 m³/h, a maximum spraying height of 17 m and a forward spraying distance of 14 m. XCMG highlights stable positioning and a smooth spraying process. These features are relevant to consistent application, while actual output depends on the concrete, operating arrangement and conditions at the work face.",
    "Tunnel lining, underground support and suitable sprayed-concrete surfaces are practical applications to evaluate. Matching the working reach to the surface geometry helps establish where the machine can operate effectively. The concrete-supply and spraying sequence should be planned together, so the XS3017S supports the required application rather than waiting for material between passes.",
    ["Wide spraying reach", "Stable positioning for controlled application", "Mechanized concrete spraying platform"],
    ["Tunnel sprayed-concrete work", "Underground support", "Suitable lining and surface applications"],
    [globalSource("product/truck-mounted-concrete-spraying-machine/xs3017s/")],
  ),
  D170: content(
    "The XCMG D170 is a bulldozer for pushing, spreading and backfilling earth and rock. It gives contractors a tracked working platform for the early stages of construction, when shaping the site and organizing material movement are the main priorities.",
    "XCMG's export-model description identifies hydrodynamic transmission, electronic gear shifting and hydraulic pilot blade control. These systems combine travel control with the blade's working movements, helping the operator manage repeated pushing and spreading tasks. The platform is intended for infrastructure earthwork rather than the loading and carrying role of a wheel loader.",
    "The stated applications include highways, railways, airports and water-conservancy construction. The D170 can be assessed for site preparation, short-distance material pushing and backfilling. Blade configuration, ground conditions and the distance material needs to move are useful factors when matching the dozer to the work and the rest of the earthmoving fleet.",
    ["Tracked platform for pushing and spreading", "Electronic shifting and pilot blade control", "Useful across infrastructure earthwork stages"],
    ["Site preparation", "Road and railway earthwork", "Backfilling and material spreading"],
    [globalSource("product/pro-detail-1193452.htm")],
  ),
  D170LGP: content(
    "The XCMG D170LGP is a low-ground-pressure bulldozer for earthwork where the supporting surface needs careful consideration. It brings the pushing and spreading role of a dozer to projects that benefit from a broader ground-contact arrangement.",
    "The official model specification lists ground-pressure configurations of 26/30 kPa, distinguishing this variant from the standard D170. XCMG describes hydrodynamic transmission, electronic gear shifting and hydraulic pilot control of the blade. These functions support the operator's control of material movement while the low-ground-pressure platform addresses how the machine's weight is distributed on the surface.",
    "Soft-ground preparation, fill spreading and water-conservancy earthwork are useful applications to evaluate. The actual ground investigation and selected track and blade configuration should guide the choice. The D170LGP is most useful when its ground-contact characteristics answer a specific site requirement rather than simply serving as an alternative to a standard dozer.",
    ["Lower ground-pressure configuration", "Pilot blade control for spreading and shaping", "Variant selected around supporting ground conditions"],
    ["Soft-ground site preparation", "Fill spreading", "Water-conservancy earthwork"],
    [globalSource("product/dozer/d170lgp/")],
  ),
  D5AT: content(
    "The XCMG D5AT is an export-market dozer for site formation and infrastructure earthwork. It combines a tracked working platform with controls intended to make repeated pushing, spreading and shaping tasks straightforward for the operator.",
    "XCMG describes hydraulic drive, electronically controlled shifting and hydraulic pilot blade control. Intelligent control and construction-data management are also listed in the model description. These features connect the machine's travel and working functions, helping the operator manage the blade and machine position through a changing earthwork sequence.",
    "The D5AT can be evaluated for urban construction, water-conservancy projects and general site preparation. Its practical role is to move and distribute material over the work area before the next construction stage. Ground conditions, required blade arrangement and access for the supporting equipment provide a useful basis for deciding how it fits within an earthmoving fleet.",
    ["Hydraulic-drive dozer platform", "Electronic shift and pilot blade controls", "Construction-data management functions"],
    ["Urban site preparation", "Water-conservancy works", "General infrastructure earthwork"],
    [globalSource("product/pro-detail-1193453.htm")],
  ),
  "D260(EUSTAGEⅠ)": content(
    "The XCMG D260(EU StageⅠ) is a dozer for excavation support, backfilling and earth-and-rock pushing. This catalog variant should be considered as a defined export configuration, with its working arrangement selected around the site's earthmoving requirements.",
    "The official Stage I model page describes hydraulic drive, electronically controlled shifting and hydraulic pilot blade control. It lists a 23,300 kg working-device weight configuration. These details place the machine in a substantial site-preparation role, with travel and blade functions coordinated for repeated pushing and spreading rather than loading material into a bucket.",
    "Highway, railway and airport earthwork are among the manufacturer's stated uses. The D260 can help organize material across larger work areas ahead of grading and compaction. Blade selection, material characteristics and pushing distance should be reviewed together, while the supplied engine and emissions configuration should remain consistent with the chosen catalog variant.",
    ["Substantial tracked earthmoving platform", "Electronic shifting and pilot blade control", "Defined Stage I export configuration"],
    ["Highway earthwork", "Railway site formation", "Backfilling and material pushing"],
    [globalSource("product/dozer/d260%28eu-Stage-1%29/")],
  ),
  "D360(EUSTAGEⅠ)": content(
    "The XCMG D360(EU StageⅠ) is listed for larger dozing and site-preparation duties. It is a model to evaluate when substantial earth-and-rock movement is central to the construction sequence and a heavier tracked platform is required.",
    "XCMG describes the D360 family for excavation, backfilling and pushing across infrastructure works. The dozer's role is to redistribute material and prepare the work area for subsequent operations. Blade arrangement and machine configuration should be matched to the expected material and pushing task, rather than transferring specifications from a different regional or emissions variant.",
    "Large site formation, highway construction and river-engineering earthwork are practical applications to assess. Planning the movement of material alongside excavation, hauling and compaction helps establish the dozer's contribution to the project. UHEEM can review the exact Stage I configuration against the workload, transport requirements and available working area.",
    ["Larger dozing platform in the catalog", "Useful for coordinated earth-and-rock movement", "Working arrangement matched to the project"],
    ["Large site formation", "Highway earthwork", "River-engineering projects"],
    [chinaSource("138548"), "src/app/_data/otherMachinerySpecifications.ts"],
    "Official D360 source is a newer desert variant. Family applications only; exact Stage I powertrain and numeric ratings not transferred.",
  ),
  XH235L: content(
    "The XCMG XH235L is a soil compactor that combines pushing and leveling with compaction. It is designed for foundation-fill operations where spreading material and preparing a dense working layer are closely connected parts of the job.",
    "The official description identifies a six-cylinder water-cooled Cummins engine and applications across road bases, dams and airports. It also describes push-leveling and compaction of landfill fill. This combination of functions gives the machine a role beyond simply passing over a prepared surface: it can be assessed as part of the process of organizing and compacting placed material.",
    "For larger earth-fill projects, the XH235L should be evaluated against the material type and construction method. Layer thickness, moisture and the required density determine how the machine is used in the rolling sequence. Matching those requirements helps the compactor support the foundation stage and the equipment working before and after it.",
    ["Pushing and leveling alongside compaction", "Cummins-powered working platform", "Useful for larger foundation-fill operations"],
    ["Road foundations", "Dam and airport fill", "Suitable landfill-fill work"],
    [globalSource("product/pro-detail-1193554.htm")],
  ),
  XH285L: content(
    "The XCMG XH285L is listed as a soil compactor for substantial fill and foundation work. It is a machine to assess when pushing, leveling and compaction need to form part of a coordinated earthwork operation.",
    "A compactor in this role should be selected around the material being placed and the density required by the construction method. Working width, ground-contact arrangement and the supplied configuration determine how it fits within the site. Reviewing these factors gives the owner a clearer way to compare it with other compaction equipment than operating weight alone.",
    "Road-foundation preparation, large fill areas and other civil earthwork are useful applications to discuss. The machine's work needs to align with layer thickness, moisture control and the agreed compaction pattern. UHEEM can review the exact XH285L variant so its configuration is matched to the material and the project sequence.",
    ["Compaction platform for substantial fill operations", "Selection coordinated with spreading and leveling", "Configuration matched to required material density"],
    ["Road-foundation work", "Large civil fill areas", "Foundation preparation"],
    ["src/app/_data/otherMachinerySpecifications.ts", globalSource("product/pro-detail-1193173.htm")],
    "Public manufacturer result is XH285, not XH285L. Numeric ratings and landfill-specific configuration not transferred to the L variant.",
  ),
  "XH365L(STAGEⅤ)": content(
    "The XCMG XH365L(Stage Ⅴ) is the Stage V compactor entry in the Nepal catalog. It is positioned for substantial pushing and compaction work, including the management of placed fill in large operating areas.",
    "XCMG's public XH365 Stage V description identifies landfill pushing and compaction as the principal application, with additional foundation-fill uses. In that role, the machine helps distribute and compact placed material within the working area. The supplied wheel, blade and engine arrangement should be reviewed for the exact catalog variant before the complete configuration is selected.",
    "Landfill operations and larger foundation-fill projects are useful applications to assess. Material behavior and the required density should guide the work pattern, while access and the layout of the operating area determine how the machine can be deployed. Matching the compactor to the task helps owners plan the daily placement and compaction sequence.",
    ["Stage V catalog option", "Pushing and compaction in the same workflow", "Relevant to substantial fill-management tasks"],
    ["Landfill-fill operations", "Large foundation fill", "Civil site preparation"],
    [globalSource("product/backfill-compactor/xh365/"), "src/app/_data/otherMachinerySpecifications.ts"],
    "Official page uses XH365(Stage V), catalog uses XH365L. Family applications retained; variant-specific dimensions and power omitted. Replaces legacy paragraph incorrectly describing XH285L Stage III.",
  ),
  "XH365L(STAGEⅢ)": content(
    "The XCMG XH365L(Stage Ⅲ) is a compactor entry for large fill-management and foundation operations. It provides an alternative emissions configuration in the catalog for projects assessing substantial pushing and compaction equipment.",
    "The manufacturer-authored XH365 Stage III literature describes landfill compaction, where reducing the volume occupied by placed material is a central operating aim. Its practical role is to combine material distribution with repeated compaction passes. The exact wheel and blade arrangement of the supplied L variant should be matched to the intended work before selection.",
    "Landfill work and larger engineered-fill areas are relevant applications to discuss. A useful equipment assessment considers the daily volume, material characteristics and the available operating space. Defining the placement sequence and compaction requirements helps establish how the XH365L Stage III configuration can fit the site's machinery and work schedule.",
    ["Stage III catalog configuration", "Material distribution and compaction workflow", "Platform assessed around substantial fill volumes"],
    ["Landfill compaction", "Engineered-fill management", "Large foundation-fill areas"],
    ["https://xcmg.net.au/wp-content/uploads/2025/11/Datasheet_Roller_XH365_Cummins_EU-Stage-%E2%85%A2_EN_20250729.pdf", "src/app/_data/otherMachinerySpecifications.ts"],
    "Manufacturer-authored source is XH365 Stage III, not an independently confirmed L variant; numeric specifications omitted.",
  ),
  XZ450E_R: content(
    "The XCMG XZ450E-R is a horizontal directional drilling rig for installing utilities along a planned underground route. It gives contractors a trenchless working method to evaluate where continuous open excavation would be difficult or disruptive.",
    "The official specification lists a 19,000 N·m maximum torque and a 600 L/min maximum mud-flow rating. These figures describe elements of the drilling system; the complete installation also depends on the selected pipe, tooling and ground conditions. The rig should be assessed together with its guidance and drilling-fluid arrangements.",
    "Utility crossings and pipeline installation are practical roles to consider. Planning the bore path, entry and exit areas and the pullback operation helps determine whether the XZ450E-R fits the project. A well-matched trenchless setup coordinates the rig with pipe handling and the support equipment needed to complete the installation.",
    ["Trenchless approach to utility installation", "Defined torque and drilling-fluid specifications", "Rig selected as part of the complete bore setup"],
    ["Utility crossings", "Pipeline installation", "Planned trenchless construction"],
    [globalSource("product/horizontal-directional-drilling-rig/xz450e-r/")],
  ),
  XZ6000F: content(
    "The XCMG XZ6000F is a large horizontal directional drilling rig for major pipeline projects. It is designed for installations where substantial thrust, pullback and rotary capability need to be coordinated with a complete trenchless construction system.",
    "XCMG lists a maximum thrust-pull force of 6,000 kN and a maximum torque of 160,000 N·m. The official description also identifies multiple power systems, a modular operating room and a separate power station. This arrangement places the model in a major-project role, where supporting services and site organization are integral to deployment.",
    "The manufacturer's stated applications include oil and natural-gas infrastructure. For any large crossing, the bore design, geology, drilling tools and fluid system should guide equipment selection. Pipe handling and the pullback sequence also deserve early planning, so the XZ6000F works as part of an organized installation package.",
    ["6,000 kN maximum thrust-pull force", "Multiple power systems for major drilling work", "Modular operating room and separate power station"],
    ["Major pipeline crossings", "Oil and gas infrastructure", "Large trenchless installation packages"],
    [globalSource("product/horizontal-directional-drilling-rig/xz6000f/")],
  ),
  XZ3000F: content(
    "The XCMG XZ3000F is a large horizontal directional drilling rig for demanding pipeline installation. It combines a substantial drilling platform with control systems intended to support the organized execution of larger trenchless work packages.",
    "XCMG describes an integrated self-loading design, electrohydraulic proportional control and load-sensitive hydraulic control. The official model page lists a 3,000 kN maximum thrust-pull force and multiple power sources. It explains that a single-engine operating mode can be used for suitable lower-demand work, while the complete power arrangement remains available for the drilling task.",
    "Larger utility crossings and pipeline projects are relevant applications to assess. The rig should be matched to the bore design and anticipated pullback requirement, with the fluid system and pipe-handling equipment specified alongside it. This gives the XZ3000F a defined role within the project rather than treating the drilling rig as a standalone purchase.",
    ["3,000 kN maximum thrust-pull force", "Electrohydraulic and load-sensitive controls", "Multiple power sources with task-dependent operation"],
    ["Larger utility crossings", "Pipeline construction", "Substantial trenchless work packages"],
    [chinaSource("136087")],
  ),
  XZ1000E: content(
    "The XCMG XZ1000E is a horizontal directional drilling rig for substantial utility and pipeline work. It offers contractors a trenchless platform to assess for crossings and installations where the bore route and ground conditions demand a carefully planned drilling method.",
    "XCMG documents the model in a European gas-pipeline river crossing involving mixed ground conditions. That manufacturer case establishes a practical pipeline-installation application without implying identical results on every site. The rig's value comes from matching its supplied configuration with suitable tooling, guidance and drilling-fluid arrangements for the proposed bore.",
    "Pipeline crossings, energy networks and larger utility projects are useful roles to evaluate. Ground investigation, route geometry and pipe characteristics should guide the equipment package. Defining the entry area, fluid management and pullback sequence helps the XZ1000E become part of a complete construction plan for the installation.",
    ["Trenchless platform for substantial pipeline work", "Manufacturer-documented crossing application", "Configuration coordinated with tooling and guidance"],
    ["Pipeline crossings", "Energy-network installation", "Larger utility projects"],
    ["https://www.xcmg.com/case/case-detail-11243009.htm"],
  ),
  XZ230E: content(
    "The XCMG XZ230E is a compact horizontal directional drilling rig for municipal utility networks. It gives contractors a smaller trenchless platform to assess when access, movement between jobs and an organized urban work area are important.",
    "XCMG's official description highlights an integrated design, relatively small size and convenient transport. The specification lists a 230 kN maximum thrust-pull force and a 115 kW engine rating. These details position the model for smaller utility-installation work, with the final choice depending on the bore path, ground conditions and pipe to be installed.",
    "Municipal pipe networks, service crossings and other planned utility routes are relevant applications. The site layout should provide the required entry and exit areas along with drilling-fluid management. Matching these arrangements to the XZ230E helps contractors evaluate a practical installation setup without assuming that maximum ratings define every possible bore.",
    ["Compact integrated drilling platform", "Transport convenience between utility jobs", "230 kN maximum thrust-pull force"],
    ["Municipal utility networks", "Service crossings", "Urban trenchless installation"],
    [globalSource("product/horizontal-directional-drilling-rig/xz230e/")],
  ),
  XZ6600: content(
    "The XCMG XZ6600 is a large horizontal directional drilling rig for long and demanding pipeline crossings. It is a specialist platform for projects that need substantial pullback capability and a coordinated drilling, fluid-management and pipe-handling system.",
    "XCMG documents the model in major pipeline work and identifies a maximum thrust-pull force of 6,600 kN. Manufacturer material describes load-sensing and electrohydraulic controls, a rack-and-pinion travel arrangement for the rotary unit and digital pressure adjustment. These functions address the control requirements of a large drilling operation rather than replacing the need for project-specific bore engineering.",
    "Major river crossings and long-distance pipeline installation are relevant roles to assess. Ground conditions, pipe characteristics and the pullback design should guide the complete equipment package. A clearly organized work site and support system allow the XZ6600 to fit the construction method required for the crossing.",
    ["6,600 kN maximum thrust-pull force", "Electrohydraulic control for large drilling operations", "Digital pressure adjustment for working functions"],
    ["Major river crossings", "Long pipeline installations", "Large infrastructure bores"],
    ["https://www.machmall.com/item-detail/xcmg-xz6600-horizontal-directional-drill-hdd-943.html", "https://www.machmall.com/content-info/27h-2640m-xcmg-set-a-new-record-for-directional-drilling-in-nigeria/1022"],
  ),
  XZ5000F: content(
    "The XCMG XZ5000F is a large horizontal directional drilling rig for substantial pipeline crossings. It combines high thrust-pull capability with an integrated platform, helping contractors evaluate a complete drilling arrangement for demanding trenchless projects.",
    "The official model page lists a 5,000 kN maximum thrust-pull force and describes electrohydraulic proportional and load-sensitive control. Multiple power systems allow operation to be adjusted to the task, including suitable lower-demand drilling stages. The manufacturer also describes a digital display and a cab with integrated controls for managing the working functions.",
    "Large-diameter pipeline installation and major utility crossings are useful applications to assess. The bore design, tooling and drilling-fluid system determine how the rig should be configured. Planning pipe handling and the final pullback operation alongside drilling helps the XZ5000F support a coordinated installation sequence.",
    ["5,000 kN maximum thrust-pull force", "Integrated platform with digital operating information", "Task-dependent use of multiple power systems"],
    ["Large pipeline installation", "Major utility crossings", "Demanding trenchless projects"],
    [chinaSource("136089")],
  ),
  XC8_S3580: content(
    "The XCMG XC8-S3580 combines loading and excavation for contractors handling varied civil work. It gives a crew one machine to assess for material handling, trench work and site preparation, reducing the need to organize each task around a separate platform.",
    "XCMG's model introduction describes load-sensitive hydraulics, reinforced working equipment and four-wheel steering with multiple modes. The manufacturer also highlights a comfortable cab and a range of optional tools. These features support a flexible working role, with the attachment and configuration selected around the tasks rather than assuming one setup suits every application.",
    "Municipal construction, road maintenance, water-related civil work and emergency-support duties are among the stated applications. The machine is particularly useful to consider when loading and digging alternate throughout a job. Access dimensions, trench geometry and the material-handling requirements provide a practical basis for choosing the XC8-S3580 configuration.",
    ["Loading and excavation on one platform", "Multiple steering modes for maneuvering", "Optional tools for varied civil work"],
    ["Municipal construction", "Road maintenance", "Water-related civil works"],
    ["https://www.xcmg.com/aboutus/news-detail.jsp?id=1128406"],
    "Source describes European launch configuration. Nepal emission tier and optional equipment availability not asserted.",
  ),
  XC8_S3570: content(
    "The XCMG XC8-S3570 is a backhoe loader for contractors who need both material loading and excavation. Its combination of front and rear working equipment is useful for civil jobs where the crew moves between digging, loading and backfilling.",
    "The official model specification lists a 1.3 m³ front bucket, a 3,500 kg rated load and a 0.26 m³ backhoe bucket. It also lists an extended digging configuration. These details help distinguish the machine within the backhoe range, while the required trench depth and loading task determine which working arrangement should be supplied.",
    "Utility excavation, construction-site preparation and road-support work are practical applications to assess. The machine's flexibility is most useful when tasks alternate within the same work area. Reviewing the access route, excavation geometry and material density helps establish how the XC8-S3570 can serve the contractor's day-to-day workload.",
    ["Front loading and rear excavation", "Larger front-bucket configuration", "Working arrangement suited to alternating tasks"],
    ["Utility excavation", "Construction-site preparation", "Road-support work"],
    [globalSource("product/backhoe-loader/xc8-s3570/")],
  ),
  XC8_C2570: content(
    "The XCMG XC8-C2570 is a backhoe loader for combining excavation and loading on civil construction jobs. It is a useful model to consider when a contractor needs a flexible machine for trenching, material movement and preparation within the same site.",
    "XCMG lists a 1.0 m³ front bucket, a 2,500 kg rated load and a 0.2 m³ backhoe bucket. The official specification also identifies a 4,440 mm maximum digging depth. These figures give a starting point for comparing the model with the required excavation and loading tasks, with the supplied working arrangement determining its practical fit.",
    "Utility trenches, building-site support and drainage works are relevant applications to evaluate. A combined loading and digging platform can help crews move between activities without waiting for separate machines. Matching the trench dimensions, access width and material-handling duties to the XC8-C2570 provides a clear basis for selection.",
    ["Loading and digging on one machine", "Defined bucket and digging-depth specification", "Useful for varied civil-construction duties"],
    ["Utility trenches", "Building-site support", "Drainage construction"],
    [globalSource("product/backhoe-loader/xc8-c2570/")],
  ),
  XC8_S2570: content(
    "The XCMG XC8-S2570 brings front loading and rear excavation together for everyday civil work. It gives contractors a versatile platform to assess for projects that alternate between digging, moving materials and restoring the work area.",
    "The official specification lists a 1.0 m³ front bucket, a 2,500 kg rated load and a 0.2 m³ backhoe bucket. XCMG emphasizes maneuverability and maintainability within the model's design priorities. The combined working arrangement is useful when the same machine needs to support more than one stage of a small or medium construction task.",
    "Roadside utility work, drainage and general site preparation are practical roles to evaluate. The most useful configuration depends on the required digging geometry, material density and available access. Reviewing these factors helps the XC8-S2570 support a varied workload while keeping the machine selection tied to the jobs the contractor actually undertakes.",
    ["Front and rear working equipment", "Versatile role across construction stages", "Maneuverability and maintainability priorities"],
    ["Roadside utilities", "Drainage works", "General site preparation"],
    [globalSource("product/backhoe-loader/xc8-s2570/")],
  ),
  XC8_S0750: content(
    "The XCMG XC8-S0750 is a compact backhoe loader for smaller loading and excavation tasks. It is useful to assess where a full-size machine would occupy too much space but a crew still needs both digging and material-handling functions.",
    "XCMG lists a 0.36 m³ front bucket, a 700 kg rated load and a 0.06 m³ backhoe bucket. The specified width is 1,612 mm, giving buyers a concrete point of comparison when reviewing site access. Its smaller working arrangement distinguishes it from the larger XC8 models and helps define the scale of job for which it should be considered.",
    "Small utility repairs, landscaping and limited-access construction support are practical applications to evaluate. The machine should be matched to trench depth, material loads and the access route. For crews with lighter, varied tasks, the XC8-S0750 offers a compact combined platform to discuss as part of their equipment plan.",
    ["Compact combined loading and digging platform", "Smaller buckets for lighter tasks", "Narrower dimensions for access planning"],
    ["Small utility repairs", "Landscaping work", "Limited-access construction support"],
    [globalSource("product/backhoe-loader/xc8-s0750/")],
  ),
  WZ30_25: content(
    "The XCMG WZ30-25 is a backhoe loader for general construction and utility work. It combines material loading at the front with excavation at the rear, giving a crew a useful way to move between tasks within a single job.",
    "The official specification lists a 1.0 m³ front bucket, a 2,500 kg rated load and a 0.3 m³ backhoe bucket. XCMG emphasizes maneuverability and maintenance convenience in the model description. The two working ends give the machine a role across excavation, stockpile handling and backfilling, with the supplied tools determining the best fit for the task.",
    "Utility installation, drainage construction and building-site support are practical applications to assess. The WZ30-25 is most useful when the daily work combines digging and material movement rather than focusing on one large production task. Reviewing access, excavation dimensions and material loads helps establish its place within the contractor's working fleet.",
    ["Loading and excavation in one platform", "Front and rear bucket arrangements", "Maneuverability and maintenance convenience"],
    ["Utility installation", "Drainage construction", "Building-site support"],
    [globalSource("product/backhoe-loader/wz30-25/")],
  ),
};

export function productEditorialKey(model: string): string {
  return model.replace(/\s+/g, "").replace(/-/g, "_").replace(/\//g, "").toUpperCase();
}

export function productEditorialForModel(model: string): ProductEditorial | undefined {
  return productEditorialByModel[productEditorialKey(model)];
}
