import type { SpecRow } from "./evSpecifications";

/** Parameter tables from “specification of road building and earth moving.xlsx”. */
export const roadEarthSpecificationsByModel: Record<string, SpecRow[]> = {
  "GR150": [{ item: "Engine model", unit: "-", parameter: "6BTA5,9-C150-II" }, { item: "Rated power/speed", unit: "kW/rpm", parameter: "112/2200" }, { item: "Machine dimension", unit: "mm", parameter: "8015 x 2380 x 3050" }, { item: "Machine weight", unit: "kg", parameter: "11200" }, { item: "Drive speed, forward", unit: "km/h", parameter: "5、8、13、20、30、42" }, { item: "Drive speed, reverse", unit: "km/h", parameter: "5、13、30" }, { item: "Traction force f=0.75", unit: "Kn", parameter: "≥59" }, { item: "Maximum gradeability", unit: "%", parameter: "≥25" }, { item: "Minimum turning radius", unit: "m", parameter: "6.6" }, { item: "Blade Length x Height", unit: "mm", parameter: "3660 x 610" }],
  "GR165": [{ item: "Engine model", unit: "-", parameter: "6BTA5.9-C180-Ⅱ" }, { item: "Rated power/speed", unit: "kW/rpm", parameter: "132/2200" }, { item: "Machine dimension", unit: "mm", parameter: "8900 x 2625 x 3420" }, { item: "Machine weight", unit: "kg", parameter: "15000" }, { item: "Drive speed, forward", unit: "km/h", parameter: "5、8、11、19、23、38" }, { item: "Drive speed, reverse", unit: "km/h", parameter: "5、11、23" }, { item: "Traction force f=0.75", unit: "Kn", parameter: "≥77" }, { item: "Maximum gradeability", unit: "%", parameter: "≥25" }, { item: "Minimum turning radius", unit: "m", parameter: "7.3" }, { item: "Blade Length x Height", unit: "mm", parameter: "3660 x 610" }, { item: "Emission", unit: "-", parameter: "EU Stage Ⅱ" }],
  "LW200KV": [{ item: "Bucket capacity", unit: "m³", parameter: "1.1" }, { item: "Operating weight", unit: "kg", parameter: "6300" }, { item: "Rated power", unit: "kW", parameter: "66" }, { item: "Rated load", unit: "kg", parameter: "2000" }, { item: "Wheelbase", unit: "mm", parameter: "2300" }, { item: "Overall Dimensions（L*W*H）", unit: "mm", parameter: "6045*2060*2950" }],
  "XC936": [{ item: "Bucket capacity", unit: "m³", parameter: "2.1" }, { item: "Operating weight", unit: "kg", parameter: "10300" }, { item: "Rated power", unit: "kW", parameter: "92" }, { item: "Rated load", unit: "kg", parameter: "3500" }, { item: "Wheelbase", unit: "mm", parameter: "2900" }, { item: "Overall Dimensions（L*W*H）", unit: "mm", parameter: "7250*2482*3100" }],
  "XC938": [{ item: "Bucket capacity", unit: "m³", parameter: "1.8" }, { item: "Operating weight", unit: "kg", parameter: "10400" }, { item: "Rated power", unit: "kW", parameter: "92" }, { item: "Rated load", unit: "kg", parameter: "3500" }, { item: "Wheelbase", unit: "mm", parameter: "2900" }, { item: "Overall Dimensions（L*W*H）", unit: "mm", parameter: "7350*2482*3220" }],
  "XC958": [{ item: "Bucket capacity", unit: "m³", parameter: "3.2" }, { item: "Operating weight", unit: "kg", parameter: "17080" }, { item: "Rated power", unit: "kW", parameter: "162" }, { item: "Rated load", unit: "kg", parameter: "5500" }, { item: "Wheelbase", unit: "mm", parameter: "3350" }, { item: "Overall Dimensions（L*W*H）", unit: "mm", parameter: "8410*2996*3455" }],
  XE140I_K: [{ item: "Operating weight", unit: "Kg", parameter: "13600" }, { item: "Rated power", unit: "kW/rpm", parameter: "75/2200" }, { item: "Engine model", unit: "-", parameter: "B3.9" }, { item: "Bucket capacity", unit: "m³", parameter: "0.65" }, { item: "Emission standard", unit: "", parameter: "National Stage Ⅱ" }, { item: "Maximum torque/speed", unit: "N.m", parameter: "637.9/1800" }, { item: "Displacement", unit: "L", parameter: "6.494" }, { item: "Travel speed", unit: "km/h", parameter: "5.16/3.03" }, { item: "Swing speed", unit: "r/min", parameter: "12.3" }, { item: "Bucket digging force", unit: "kN", parameter: "99" }, { item: "Arm digging force", unit: "kN", parameter: "74" }],
  XE215I_K: [{ item: "Operating weight", unit: "Kg", parameter: "21500" }, { item: "Rated power", unit: "kW/rpm", parameter: "104/2000" }, { item: "Engine model", unit: "-", parameter: "6BT5.9" }, { item: "Bucket capacity", unit: "m³", parameter: "1" }, { item: "Emission standard", unit: "", parameter: "National Stage Ⅱ" }, { item: "Maximum torque/speed", unit: "N.m", parameter: "564/1600" }, { item: "Displacement", unit: "L", parameter: "5.9" }, { item: "Travel speed", unit: "km/h", parameter: "5.2/2.8" }, { item: "Swing speed", unit: "r/min", parameter: "13" }, { item: "Bucket digging force", unit: "kN", parameter: "150" }, { item: "Arm digging force", unit: "kN", parameter: "131" }],
  "XE230CLC": [{ item: "Operating weight", unit: "Kg", parameter: "23000" }, { item: "Rated power", unit: "kW/rpm", parameter: "128.5" }, { item: "Engine model", unit: "-", parameter: "ISUZU CC-6BG1TRP" }, { item: "Bucket capacity", unit: "m³", parameter: "1" }, { item: "Emission standard", unit: "", parameter: "National Stage Ⅱ" }, { item: "Maximum torque/speed", unit: "N.m", parameter: "637.9/1800" }, { item: "Displacement", unit: "L", parameter: "6.494" }, { item: "Travel speed", unit: "km/h", parameter: "5.5/3.3" }, { item: "Swing speed", unit: "r/min", parameter: "13.2" }, { item: "Bucket digging force", unit: "kN", parameter: "149" }, { item: "Arm digging force", unit: "kN", parameter: "111" }],
  "XE380C": [{ item: "Operating weight", unit: "Kg", parameter: "36600" }, { item: "Rated power", unit: "hp/rpm", parameter: "259/2200" }, { item: "Engine model", unit: "-", parameter: "6BT5.9" }, { item: "Bucket capacity", unit: "m³", parameter: "1" }, { item: "Emission standard", unit: "", parameter: "National Stage Ⅱ" }, { item: "Maximum torque/speed", unit: "rpm", parameter: "873/1700" }, { item: "Displacement", unit: "L", parameter: "7.79" }, { item: "Travel speed", unit: "km/h", parameter: "5.4" }, { item: "Swing speed", unit: "rpm", parameter: "9.7" }, { item: "Bucket digging force", unit: "kN", parameter: "" }, { item: "Arm digging force", unit: "kN", parameter: "" }],
  "XP163": [{ item: "Engine", unit: "-", parameter: "Shangchai" }, { item: "Emission", unit: "-", parameter: "Stage Ⅱ" }, { item: "Operating Weight", unit: "kg", parameter: "16000" }, { item: "Dimensions", unit: "mm", parameter: "4,780 x 2,232 x 3,340" }, { item: "Working speed", unit: "km/h", parameter: "0～4.5;0～8.7;0～18.4 / 0~4.5;0~8.7" }, { item: "Gradeability", unit: "%", parameter: "30" }, { item: "Wheelbase", unit: "mm", parameter: "3700" }, { item: "Drum width", unit: "mm", parameter: "2055" }],
  "ZL30E": [{ item: "Bucket capacity", unit: "m³", parameter: "1.8" }, { item: "Operating weight", unit: "kg", parameter: "10800" }, { item: "Rated power", unit: "kW", parameter: "92" }, { item: "Rated load", unit: "kg", parameter: "3500" }, { item: "Wheelbase", unit: "mm", parameter: "2900" }, { item: "Overall Dimensions（L*W*H）", unit: "mm", parameter: "7370*2482*3320" }],
  "XTR4/260": [
    { item: "Overall weight", unit: "t", parameter: "80" },
    { item: "Dimensions Length (including second conveyor)", unit: "mm", parameter: "12300/19100" },
    { item: "Width Shovel", unit: "mm", parameter: "2300/3200" },
    { item: "Machine body", unit: "mm", parameter: "2100" },
    { item: "Height Max.height of cutting head placed horizontally", unit: "mm", parameter: "2250" },
    { item: "Machine body", unit: "mm", parameter: "1820" },
    { item: "Positioning cutting range Height", unit: "mm", parameter: "4520" },
    { item: "Width", unit: "mm", parameter: "4970" },
    { item: "Area", unit: "m²", parameter: "/" },
    { item: "Dinting depth", unit: "mm", parameter: "200" },
    { item: "Ground clearance", unit: "mm", parameter: "233" },
    { item: "Gantry height", unit: "mm", parameter: "380" },
    { item: "Traveling speed", unit: "m/min", parameter: "0-7" },
    { item: "Power of cutting motor", unit: "kW", parameter: "260/200" },
    { item: "Power of pump station motor", unit: "kW", parameter: "132" },
    { item: "Power supply voltage", unit: "V", parameter: "AC1140" },
    { item: "Power supply frequency", unit: "Hz", parameter: "50" },
    { item: "Loading capacity", unit: "m²/min", parameter: "Star wheel type/3.2" },
    { item: "Waterspray pressure", unit: "MPa", parameter: "4" },
  ],
  "XTR6/280": [
    { item: "Overall weight", unit: "t", parameter: "100" },
    { item: "Dimensions Length (including second conveyor)", unit: "mm", parameter: "15500" },
    { item: "Width Shovel", unit: "mm", parameter: "3600" },
    { item: "Machine body", unit: "mm", parameter: "2780" },
    { item: "Height Max.height of cutting head placed horizontally", unit: "mm", parameter: "3518" },
    { item: "Main frame", unit: "mm", parameter: "2395" },
    { item: "Positioning cutting range Height", unit: "mm", parameter: "6500" },
    { item: "Width", unit: "mm", parameter: "6300" },
    { item: "Dinting depth", unit: "mm", parameter: "206" },
    { item: "Ground clearance", unit: "mm", parameter: "270" },
    { item: "Gantry height", unit: "mm", parameter: "400" },
    { item: "Traveling speed", unit: "m/min", parameter: "8" },
    { item: "Power of cutting motor", unit: "kW", parameter: "280/220" },
    { item: "Power of pump station motor", unit: "kW", parameter: "160" },
    { item: "Power supply voltage", unit: "V", parameter: "AC1140" },
    { item: "Power supply frequency", unit: "Hz", parameter: "50" },
    { item: "Loading capacity", unit: "m²/min", parameter: "/8" },
    { item: "Waterspray pressure", unit: "MPa", parameter: "≥2" },
  ],
  "XTR7/360": [
    { item: "Overall weight", unit: "t", parameter: "145" },
    { item: "Dimensions Length (including second conveyor)", unit: "mm", parameter: "17490" },
    { item: "Width Shovel", unit: "mm", parameter: "3800" },
    { item: "Machine body", unit: "mm", parameter: "3300" },
    { item: "Height Max.height of cutting head placed horizontally", unit: "mm", parameter: "4110" },
    { item: "Machine body", unit: "mm", parameter: "2600" },
    { item: "Positioning cutting range Height", unit: "mm", parameter: "7000" },
    { item: "Width", unit: "mm", parameter: "7200" },
    { item: "Area", unit: "m²", parameter: "/" },
    { item: "Dinting depth", unit: "mm", parameter: "350" },
    { item: "Ground clearance", unit: "mm", parameter: "450" },
    { item: "Gantry height", unit: "mm", parameter: "420" },
    { item: "Traveling speed", unit: "m/min", parameter: "6" },
    { item: "Power of cutting motor", unit: "kW", parameter: "360/280" },
    { item: "Power of pump station motor", unit: "kW", parameter: "230" },
    { item: "Power supply voltage", unit: "V", parameter: "AC1140" },
    { item: "Power supply frequency", unit: "Hz", parameter: "50" },
    { item: "Loading capacity", unit: "m³/min", parameter: "Star wheel type/8.0" },
    { item: "Waterspray pressure", unit: "MPa", parameter: "≥2" },
  ],
  "XUD135": [
    { item: "Engine Brand", unit: "/", parameter: "Yuchai" },
    { item: "Engine Model", unit: "/", parameter: "YCF3090-T481" },
    { item: "Engine Rated power", unit: "Kw", parameter: "66" },
    { item: "Engine Emission standard", unit: "/", parameter: "China Stage IV" },
    { item: "Rock drill Brand/安百拓/蒙特贝", unit: "/", parameter: "XCMG" },
    { item: "Rock drill Model", unit: "/", parameter: "18U/HC109/XHD20" },
    { item: "Rock drill Impact power", unit: "kW", parameter: "18/18/20" },
    { item: "Drill boom Boom extension", unit: "mm", parameter: "1250" },
    { item: "Drill boom Feed extension", unit: "mm", parameter: "1250" },
    { item: "Feed beam Total length", unit: "mm", parameter: "5437/5986" },
    { item: "Feed beam Drill steel length", unit: "mm", parameter: "3700/4305" },
    { item: "Feed beam Single-pass drilling depth", unit: "mm", parameter: "3400/4000" },
    { item: "Water system Rated flow", unit: "m3/h", parameter: "5" },
    { item: "Water system Min. water inlet pressure", unit: "bar", parameter: "2" },
    { item: "Air system Flow", unit: "L/min", parameter: "600/700" },
    { item: "Air system Pressure", unit: "bar", parameter: "8" },
    { item: "Electrical system Voltage", unit: "V", parameter: "380" },
    { item: "Electrical system Frequency", unit: "Hz", parameter: "50" },
    { item: "Electrical system Cable length", unit: "m", parameter: "80" },
    { item: "Chassis Gradeability", unit: "°", parameter: "14" },
    { item: "Chassis Traveling speed", unit: "km/h", parameter: "15/18" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "11860×2065×2420" },
  ],
  "XTD275": [
    { item: "Engine Manufacturer", unit: "/", parameter: "Cummins" },
    { item: "Engine Model", unit: "/", parameter: "" },
    { item: "Engine Rated power", unit: "Kw", parameter: "110" },
    { item: "Engine Emission standard", unit: "/", parameter: "CN IV" },
    { item: "Rock drill Brand/安百拓/蒙特贝", unit: "/", parameter: "Montabert HC 109" },
    { item: "Rock drill Model", unit: "/", parameter: "HC 109" },
    { item: "Rock drill Impact power", unit: "kW", parameter: "18.8" },
    { item: "Drill boom Boom extension", unit: "mm", parameter: "1250" },
    { item: "Drill boom Feed extension", unit: "mm", parameter: "1800" },
    { item: "Feed beam Total length", unit: "mm", parameter: "6012" },
    { item: "Feed beam Drill steel length", unit: "mm", parameter: "4310" },
    { item: "Feed beam Single-pass drilling depth", unit: "mm", parameter: "4000" },
    { item: "Water system Rated flow", unit: "m3/h", parameter: "10" },
    { item: "Water system Min. water inlet pressure", unit: "bar", parameter: "2" },
    { item: "Air system Flow", unit: "L/min", parameter: "700" },
    { item: "Air system Pressure", unit: "bar", parameter: "8" },
    { item: "Electrical system Voltage", unit: "V", parameter: "380" },
    { item: "Electrical system Frequency", unit: "Hz", parameter: "50" },
    { item: "Electrical system Cable length", unit: "m", parameter: "60" },
    { item: "Chassis Gradeability", unit: "°", parameter: "14" },
    { item: "Chassis Traveling speed", unit: "km/h", parameter: "15" },
    { item: "Total Weight", unit: "t", parameter: "27.4" },
  ],
  "XUD275": [
    { item: "Engine Manufacturer", unit: "/", parameter: "Cummins" },
    { item: "Engine Model", unit: "/", parameter: "" },
    { item: "Engine Rated power", unit: "Kw", parameter: "110" },
    { item: "Engine Emission standard", unit: "/", parameter: "CN IV" },
    { item: "Rock drill Brand/安百拓/蒙特贝", unit: "/", parameter: "Montabert HC 109" },
    { item: "Rock drill Model", unit: "/", parameter: "HC 109" },
    { item: "Rock drill Impact power", unit: "kW", parameter: "18.8" },
    { item: "Drill boom Boom extension", unit: "mm", parameter: "1250" },
    { item: "Drill boom Feed extension", unit: "mm", parameter: "1800" },
    { item: "Feed beam Total length", unit: "mm", parameter: "6012" },
    { item: "Feed beam Drill steel length", unit: "mm", parameter: "4310" },
    { item: "Feed beam Single-pass drilling depth", unit: "mm", parameter: "4000" },
    { item: "Water system Rated flow", unit: "m3/h", parameter: "10" },
    { item: "Water system Min. water inlet pressure", unit: "bar", parameter: "2" },
    { item: "Air system Flow", unit: "L/min", parameter: "700" },
    { item: "Air system Pressure", unit: "bar", parameter: "8" },
    { item: "Electrical system Voltage", unit: "V", parameter: "380" },
    { item: "Electrical system Frequency", unit: "Hz", parameter: "50" },
    { item: "Electrical system Cable length", unit: "m", parameter: "60" },
    { item: "Chassis Gradeability", unit: "°", parameter: "14" },
    { item: "Chassis Traveling speed", unit: "km/h", parameter: "15" },
    { item: "Total Weight", unit: "t", parameter: "27.4" },
  ],
  "XTD295": [
    { item: "Engine Manufacturer", unit: "/", parameter: "Cummins" },
    { item: "Engine Model", unit: "/", parameter: "" },
    { item: "Engine Rated power", unit: "Kw", parameter: "140" },
    { item: "Engine Emission standard", unit: "/", parameter: "EU V" },
    { item: "Rock drill Brand/安百拓/蒙特贝", unit: "/", parameter: "Montabert HC109" },
    { item: "Rock drill Model", unit: "/", parameter: "HC109" },
    { item: "Rock drill Impact power", unit: "kW", parameter: "18.8" },
    { item: "Drill boom Boom extension", unit: "mm", parameter: "1600" },
    { item: "Drill boom Feed extension", unit: "mm", parameter: "1800" },
    { item: "Feed beam Total length", unit: "mm", parameter: "7240" },
    { item: "Feed beam Drill steel length", unit: "mm", parameter: "5525" },
    { item: "Feed beam Single-pass drilling depth", unit: "mm", parameter: "5217" },
    { item: "Water system Rated flow", unit: "m3/h", parameter: "10" },
    { item: "Water system Min. water inlet pressure", unit: "bar", parameter: "2" },
    { item: "Air system Flow", unit: "L/min", parameter: "1150" },
    { item: "Air system Pressure", unit: "bar", parameter: "8" },
    { item: "Electrical system Voltage", unit: "V", parameter: "380" },
    { item: "Electrical system Frequency", unit: "Hz", parameter: "50" },
    { item: "Electrical system Cable length", unit: "m", parameter: "80" },
    { item: "Chassis Gradeability", unit: "°", parameter: "14" },
    { item: "Chassis Traveling speed", unit: "km/h", parameter: "15" },
    { item: "Total weight", unit: "t", parameter: "35.4" },
  ],
  "XUD295": [
    { item: "Engine Manufacturer", unit: "/", parameter: "Cummins" },
    { item: "Engine Model", unit: "/", parameter: "" },
    { item: "Engine Rated power", unit: "Kw", parameter: "140" },
    { item: "Engine Emission standard", unit: "/", parameter: "EU V" },
    { item: "Rock drill Brand/安百拓/蒙特贝", unit: "/", parameter: "Montabert HC109" },
    { item: "Rock drill Model", unit: "/", parameter: "HC109" },
    { item: "Rock drill Impact power", unit: "kW", parameter: "18.8" },
    { item: "Drill boom Boom extension", unit: "mm", parameter: "1600" },
    { item: "Drill boom Feed extension", unit: "mm", parameter: "1800" },
    { item: "Feed beam Total length", unit: "mm", parameter: "7240" },
    { item: "Feed beam Drill steel length", unit: "mm", parameter: "5525" },
    { item: "Feed beam Single-pass drilling depth", unit: "mm", parameter: "5217" },
    { item: "Water system Rated flow", unit: "m3/h", parameter: "10" },
    { item: "Water system Min. water inlet pressure", unit: "bar", parameter: "2" },
    { item: "Air system Flow", unit: "L/min", parameter: "1150" },
    { item: "Air system Pressure", unit: "bar", parameter: "8" },
    { item: "Electrical system Voltage", unit: "V", parameter: "380" },
    { item: "Electrical system Frequency", unit: "Hz", parameter: "50" },
    { item: "Electrical system Cable length", unit: "m", parameter: "80" },
    { item: "Chassis Gradeability", unit: "°", parameter: "14" },
    { item: "Chassis Traveling speed", unit: "km/h", parameter: "15" },
    { item: "Total weight", unit: "t", parameter: "35.4" },
  ],
  SQS68TL_4: [
    { item: "Model", unit: "-", parameter: "SQS68TL_4" },
    { item: "Chassis", unit: "-", parameter: "ZZ1148E4515C1R (right hand drive)" },
    { item: "Overall dimension", unit: "mm", parameter: "8000×2300×3510mm" },
    { item: "Carriage dimension", unit: "mm", parameter: "500×2294×550mm" },
    { item: "Model of engine", unit: "-", parameter: "YC4D130-33" },
    { item: "Engine Power", unit: "hp", parameter: "130" },
    { item: "Emission standard", unit: "-", parameter: "Euro II" },
    { item: "Max. Lifting moment", unit: "T.M", parameter: "6.72" },
    { item: "Max. Lifting capacity", unit: "kg/m", parameter: "3200 / 2.1" },
    { item: "Boom length", unit: "m", parameter: "Min. 3.645  ~ Max.10.17" },
    { item: "Slewing gear type", unit: "-", parameter: "Hyd. motor driven, combined type of planetary gear and worm gear" },
    { item: "Hydraulic oil tank capacity", unit: "l", parameter: "60" },
  ],
  /** Excel sheet for SQS68TL_5 is empty; use SQS68TL_4 specification set as nearest available reference. */
  SQS68TL_5: [
    { item: "Model", unit: "-", parameter: "SQS68TL_4" },
    { item: "Chassis", unit: "-", parameter: "ZZ1148E4515C1R (right hand drive)" },
    { item: "Overall dimension", unit: "mm", parameter: "8000×2300×3510mm" },
    { item: "Carriage dimension", unit: "mm", parameter: "500×2294×550mm" },
    { item: "Model of engine", unit: "-", parameter: "YC4D130-33" },
    { item: "Engine Power", unit: "hp", parameter: "130" },
    { item: "Emission standard", unit: "-", parameter: "Euro II" },
    { item: "Max. Lifting moment", unit: "T.M", parameter: "6.72" },
    { item: "Max. Lifting capacity", unit: "kg/m", parameter: "3200 / 2.1" },
    { item: "Boom length", unit: "m", parameter: "Min. 3.645  ~ Max.10.17" },
    { item: "Slewing gear type", unit: "-", parameter: "Hyd. motor driven, combined type of planetary gear and worm gear" },
    { item: "Hydraulic oil tank capacity", unit: "l", parameter: "60" },
  ],
  SQS125TL_4: [
    { item: "Model", unit: "-", parameter: "SQS125TL_4" },
    { item: "Overall dimension", unit: "mm", parameter: "" },
    { item: "Carriage dimension", unit: "mm", parameter: "" },
    { item: "Model of engine", unit: "-", parameter: "" },
    { item: "Engine Power", unit: "hp", parameter: "" },
    { item: "Weight", unit: "kg", parameter: "1850" },
    { item: "Max. Lifting moment", unit: "T.M", parameter: "12.625" },
    { item: "Max. Lifting capacity", unit: "kg/m", parameter: "5050 / 2.5" },
    { item: "Boom length", unit: "m", parameter: "Min. 3.75 m ~ Max.11.24 m" },
    { item: "Slewing gear type", unit: "-", parameter: "Hyd. motor driven,  planetary gear speed reduction provided with mechanical brake" },
    { item: "Hydraulic oil tank capacity", unit: "l", parameter: "90" },
    { item: "Hydraulic system Rated pressure", unit: "Mpa", parameter: "22" },
  ],
  "SQS157ETL-4": [
    { item: "Model", unit: "-", parameter: "SQS157TL-4" },
    { item: "Chassis", unit: "-", parameter: "" },
    { item: "Overall dimension", unit: "mm", parameter: "" },
    { item: "Carriage dimension", unit: "mm", parameter: "" },
    { item: "Model of engine", unit: "-", parameter: "" },
    { item: "Engine Power", unit: "hp", parameter: "" },
    { item: "Emission standard", unit: "-", parameter: "" },
    { item: "Max. Lifting moment", unit: "kN.m", parameter: "157.5" },
    { item: "Max. Lifting capacity", unit: "kg/m", parameter: "3200 / 2.1" },
    { item: "Boom length", unit: "m", parameter: "Min. 3.78~ Max. 11.24" },
    { item: "Slewing gear type", unit: "-", parameter: "" },
    { item: "Hydraulic oil tank capacity", unit: "l", parameter: "90" },
  ],
  "XCT25_Y1": [
    { item: "Max. load capacity", unit: "t", parameter: "25" },
    { item: "Telescopic boom", unit: "m", parameter: "33.5" },
    { item: "Number of axles", unit: "-", parameter: "3" },
    { item: "Max. hoist height", unit: "m", parameter: "41.6" },
    { item: "Max.load moment", unit: "kN.m", parameter: "941" },
    { item: "Drive engine model", unit: "-", parameter: "SC7H260Q3" },
    { item: "Drive engine power", unit: "kw", parameter: "192" },
    { item: "Drive/Steering", unit: "-", parameter: "4x2" },
    { item: "Driving speed", unit: "km/h", parameter: "85" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "24510" },
    { item: "Dimensions", unit: "mm", parameter: "12207×2500×3450" },
    { item: "Emission standard", unit: "-", parameter: "CHINA III" },
  ],
  XCT25L4_Y: [
    { item: "Model", unit: "-", parameter: "XCT25L4_Y" },
    { item: "Max. load capacity", unit: "t", parameter: "25" },
    { item: "Telescopic boom", unit: "m", parameter: "33.5" },
    { item: "Number of axles", unit: "-", parameter: "3" },
    { item: "Max. hoist height", unit: "m", parameter: "44.7" },
    { item: "Max.load moment", unit: "kN.m", parameter: "931" },
    { item: "Drive engine model", unit: "-", parameter: "SC7H200G4A" },
    { item: "Drive engine power", unit: "kw", parameter: "149" },
    { item: "Drive/Steering", unit: "-", parameter: "6×4×2" },
    { item: "Driving speed", unit: "km/h", parameter: "50" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "25000 / 26000" },
    { item: "Dimensions", unit: "mm", parameter: "12245×2550×3395" },
    { item: "Emission standard", unit: "-", parameter: "BS-IV" },
  ],
  "XCT50_Y1": [
    { item: "Max. load capacity", unit: "t", parameter: "50" },
    { item: "Telescopic boom", unit: "m", parameter: "44.9" },
    { item: "Number of axles", unit: "-", parameter: "4" },
    { item: "Max. hoist height", unit: "m", parameter: "60.1" },
    { item: "Max.load moment", unit: "kN.m", parameter: "1600" },
    { item: "Drive engine model", unit: "-", parameter: "WP8G350E670" },
    { item: "Drive engine power", unit: "kw", parameter: "257" },
    { item: "Drive/Steering", unit: "-", parameter: "8x4x4" },
    { item: "Driving speed", unit: "km/h", parameter: "48" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "39000" },
    { item: "Dimensions", unit: "mm", parameter: "14375×2650×3520" },
    { item: "Emission standard", unit: "-", parameter: "India V" },
  ],
  XCT80_Y1: [
    { item: "Max. load capacity", unit: "t", parameter: "80" },
    { item: "Telescopic boom", unit: "m", parameter: "50.5" },
    { item: "Number of axles", unit: "-", parameter: "4" },
    { item: "Max. hoist height", unit: "m", parameter: "65" },
    { item: "Max.load moment", unit: "kN.m", parameter: "2965" },
    { item: "Drive engine model", unit: "-", parameter: "WP10HG350E670" },
    { item: "Drive engine power", unit: "kw", parameter: "257" },
    { item: "Drive/Steering", unit: "-", parameter: "8x4x4" },
    { item: "Driving speed", unit: "km/h", parameter: "48" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "46900" },
    { item: "Dimensions", unit: "mm", parameter: "14985×2800×3790" },
    { item: "Emission standard", unit: "-", parameter: "BS-V" },
  ],
  XCT110_Y2: [
    { item: "Max. load capacity", unit: "t", parameter: "110" },
    { item: "Telescopic boom", unit: "m", parameter: "60.5" },
    { item: "Number of axles", unit: "-", parameter: "4" },
    { item: "Max. hoist height", unit: "m", parameter: "85" },
    { item: "Max.load moment", unit: "kN.m", parameter: "3528" },
    { item: "Drive engine model", unit: "-", parameter: "WP10HG350E670 (Weichai)" },
    { item: "Drive engine power", unit: "kw", parameter: "257" },
    { item: "Drive/Steering", unit: "-", parameter: "8x4x4" },
    { item: "Driving speed", unit: "km/h", parameter: "48" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "49300" },
    { item: "Dimensions", unit: "mm", parameter: "15000×2800×3825" },
    { item: "Emission standard", unit: "-", parameter: "BS-V emission standard" },
  ],
  XCT110_Y: [
    { item: "Max. load capacity", unit: "t", parameter: "110" },
    { item: "Telescopic boom", unit: "m", parameter: "60.5" },
    { item: "Number of axles", unit: "-", parameter: "4" },
    { item: "Max. hoist height", unit: "m", parameter: "85" },
    { item: "Max.load moment", unit: "kN.m", parameter: "1679" },
    { item: "Drive engine model", unit: "-", parameter: "WP10H375E50" },
    { item: "Drive engine power", unit: "kw", parameter: "276" },
    { item: "Drive/Steering", unit: "-", parameter: "8x4x4" },
    { item: "Driving speed", unit: "km/h", parameter: "≥80" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "49800" },
    { item: "Dimensions", unit: "mm", parameter: "15000*2800*3927" },
    { item: "Emission standard", unit: "-", parameter: "Euro V" },
  ],
  /** Catalog lists XCT110_Y1; Excel provides XCT110_Y and XCT110_Y2—use XCT110_Y as closest available spec set. */
  XCT110_Y1: [
    { item: "Max. load capacity", unit: "t", parameter: "110" },
    { item: "Telescopic boom", unit: "m", parameter: "60.5" },
    { item: "Number of axles", unit: "-", parameter: "4" },
    { item: "Max. hoist height", unit: "m", parameter: "85" },
    { item: "Max.load moment", unit: "kN.m", parameter: "1679" },
    { item: "Drive engine model", unit: "-", parameter: "WP10H375E50" },
    { item: "Drive engine power", unit: "kw", parameter: "276" },
    { item: "Drive/Steering", unit: "-", parameter: "8x4x4" },
    { item: "Driving speed", unit: "km/h", parameter: "≥80" },
    { item: "Dead Weight in Travel State", unit: "kg", parameter: "49800" },
    { item: "Dimensions", unit: "mm", parameter: "15000*2800*3927" },
    { item: "Emission standard", unit: "-", parameter: "Euro V" },
  ],
  XR138E: [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1500" },
    { item: "Max. drilling depth", unit: "m", parameter: "45" },
    { item: "Engine Brand", unit: "-", parameter: "Cummins" },
    { item: "Engine Model", unit: "-", parameter: "B5.9" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "133" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "138" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "6-45" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "60" },
    { item: "Main winch wire rope diameter", unit: "mm", parameter: "16" },
    { item: "Main winch Max.speed", unit: "m/min", parameter: "75" },
    { item: "Chassis Track width", unit: "mm", parameter: "600" },
    { item: "Chassis Track widening", unit: "mm", parameter: "2250-3650" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "1.5" },
  ],
  "XR130E": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1500/1300" },
    { item: "Max. drilling depth", unit: "m", parameter: "40/50" },
    { item: "Engine Brand", unit: "-", parameter: "CUMMINS" },
    { item: "Engine Model", unit: "-", parameter: "QSB7" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "169" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "130" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "8-35" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "120" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "140" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "3.5" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "140" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "75" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "26" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "50" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "70" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "16" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±3/5/90" },
    { item: "Chassis Max.span of track", unit: "mm", parameter: "2500-3600" },
    { item: "Chassis Track shoe width", unit: "mm", parameter: "600" },
    { item: "Chassis Track length", unit: "mm", parameter: "4667" },
    { item: "Chassis Max.gradeability", unit: "%", parameter: "40" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "2.7" },
    { item: "Hydraulic system Working pressure", unit: "Mpa", parameter: "35" },
    { item: "Hydraulic system Operating weight", unit: "t", parameter: "43" },
    { item: "Dimensions Working state", unit: "mm", parameter: "7546×3600×17724" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "14097×2500×3500" },
  ],
  "XR158E": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1500" },
    { item: "Max. drilling depth", unit: "m", parameter: "45/36" },
    { item: "Engine Brand", unit: "-", parameter: "CUMMINS" },
    { item: "Engine Model", unit: "-", parameter: "QSB5.9" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "133" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "158" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "6-35" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "130" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "160" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "3.7" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "150" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "80" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "28" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "60" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "75" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "16" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±3/5/90" },
    { item: "Chassis Max.span of track", unit: "mm", parameter: "1.5" },
    { item: "Chassis Track shoe width", unit: "mm", parameter: "35" },
    { item: "Chassis Track length", unit: "mm", parameter: "600" },
    { item: "Chassis Max.gradeability", unit: "%", parameter: "4660" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "2550-3650" },
    { item: "Hydraulic system Working pressure", unit: "Mpa", parameter: "35" },
    { item: "Hydraulic system Operating weight", unit: "t", parameter: "42" },
    { item: "Dimensions Working state", unit: "mm", parameter: "7900×3650×15800" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "14480×2550×3500" },
  ],
  "XR178E": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1500" },
    { item: "Max. drilling depth", unit: "m", parameter: "56/44" },
    { item: "Engine Model", unit: "-", parameter: "QSB5.9" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "169" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "178" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "6-38" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "160" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "180" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "4.2" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "170" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "80" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "28" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "60" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "80" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "16" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±3/5/90" },
    { item: "Chassis Max.span of track", unit: "mm", parameter: "1.5" },
    { item: "Chassis Track shoe width", unit: "mm", parameter: "35" },
    { item: "Chassis Track length", unit: "mm", parameter: "600" },
    { item: "Chassis Max.gradeability", unit: "%", parameter: "4660" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "2550-3650" },
    { item: "Hydraulic system Working pressure", unit: "Mpa", parameter: "32" },
    { item: "Hydraulic system Operating weight", unit: "t", parameter: "52" },
    { item: "Dimensions Working state", unit: "mm", parameter: "8205×4200×19208" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "14442×2960×3555" },
  ],
  "XR210I": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1800" },
    { item: "Max. drilling depth", unit: "m", parameter: "65" },
    { item: "Engine Brand", unit: "-", parameter: "CUMMINS" },
    { item: "Engine Model", unit: "-", parameter: "QSB6.7" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "194" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "210" },
    { item: "Rotary drive Working speed", unit: "rpm", parameter: "5-30" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "180" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "190" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "5" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "216" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "60" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "28" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "80" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "57" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "20" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±3/5/15" },
  ],
  "XR218E": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "1800" },
    { item: "Max. drilling depth", unit: "m", parameter: "65/50" },
    { item: "Engine Brand", unit: "-", parameter: "QSB6.7" },
    { item: "Engine Model", unit: "-", parameter: "CUMMINS" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "194" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "218" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "5-30" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "180" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "190" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "5" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "216" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "80" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "28" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "80" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "57" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "20" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±3/5/90" },
    { item: "Chassis Max.span of track", unit: "mm", parameter: "1.5" },
    { item: "Chassis Track shoe width", unit: "mm", parameter: "35" },
    { item: "Chassis Track length", unit: "mm", parameter: "700" },
    { item: "Chassis Max.gradeability", unit: "%", parameter: "5145" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "2960-4200" },
    { item: "Hydraulic system Working pressure", unit: "Mpa", parameter: "35" },
    { item: "Hydraulic system Operating weight", unit: "t", parameter: "62" },
    { item: "Dimensions Working state", unit: "mm", parameter: "8350×4200×21480" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "15370×2960×3490" },
  ],
  "XR240E": [
    { item: "Max. drilling diameter", unit: "mm", parameter: "2200/2000" },
    { item: "Max. drilling depth", unit: "m", parameter: "56/80" },
    { item: "Engine Brand", unit: "-", parameter: "Isuzu" },
    { item: "Engine Model", unit: "-", parameter: "6UZ1X-270" },
    { item: "Engine Ratedpower", unit: "kW", parameter: "270" },
    { item: "Rotary drive Rated output torque", unit: "kNm", parameter: "240" },
    { item: "Rotary drive Working speed", unit: "r/min", parameter: "7-30" },
    { item: "Crowd cylinder Max crowd force", unit: "kN", parameter: "220" },
    { item: "Crowd cylinder Max lifting force", unit: "kN", parameter: "270" },
    { item: "Crowd cylinder Max.stroke", unit: "m", parameter: "5" },
    { item: "Main winch Max.lifting force", unit: "kN", parameter: "240" },
    { item: "Main winch Max.line speed", unit: "m/min", parameter: "270" },
    { item: "Main winch Wire ropediameter", unit: "mm", parameter: "32" },
    { item: "Auxiliary winch Max.lifting force", unit: "kN", parameter: "80" },
    { item: "Auxiliary winch Max.line speed", unit: "m/min", parameter: "70" },
    { item: "Auxiliary winch Wire rope diameter", unit: "mm", parameter: "20" },
    { item: "Mast inclination Lateral/Forward/ Backward", unit: "°", parameter: "±4/5/1990" },
    { item: "Chassis Max.span of track", unit: "mm", parameter: "3250-4400" },
    { item: "Chassis Track shoe width", unit: "mm", parameter: "800" },
    { item: "Chassis Track length", unit: "mm", parameter: "5715" },
    { item: "Chassis Max.gradeability", unit: "%", parameter: "35" },
    { item: "Chassis Max traveling speed", unit: "km/h", parameter: "1.5" },
    { item: "Hydraulic system Working pressure", unit: "Mpa", parameter: "35" },
    { item: "Hydraulic system Operating weight", unit: "t", parameter: "84" },
    { item: "Dimensions Working state", unit: "mm", parameter: "8870×4400×22800" },
    { item: "Dimensions Transport state", unit: "mm", parameter: "17525×3250×3594" },
  ],
};

/** PRODUCT DESCRIPTION copy from the same workbook (when provided per sheet). */
export const roadEarthDescriptionsByModel: Record<string, string> = {
  "GR150": "The XCMG GR150 motor grader is mainly used for operations such as ground leveling, ditching, slope shaping, bulldozing, scarifying, and snow removal over wide areas including highways, airports, and agricultural fields. It is also suitable for handling moderate to heavy-duty working conditions with consistent performance.\n\nWith its compact structure and reliable operation, the GR150 plays an important role in various construction activities such as road building in urban and rural areas, water conservancy projects, farmland development, and other general infrastructure works.",
  "GR165": "The GR165 motor grader is primarily designed for tasks such as surface leveling, ditch formation, slope trimming, bulldozing, scarifying, and snow clearing across large areas like highways, airports, and agricultural land. It is also capable of operating under demanding, heavy-duty conditions.\n\nWith its compact design and dependable performance, this machine plays a vital role in construction activities, including national defense projects, urban and rural road development, water resource engineering, and farmland enhancement.",
  "LW200KV":
    "The XCMG machine features durable heavy-duty structural components designed for demanding environments. Advanced engineering and fatigue testing ensure strength and reliability, while the water treatment system helps improve air quality during underground operations.\n\nIts adjustable cab design enhances adaptability to different working conditions, and optional attachments such as a larger bucket, extended boom, and side-dumping device provide greater operational flexibility.",
  "XC936": "",
  "XC938": "The XC938 is a next-generation specialized lifting product introduced by XCMG Construction Machinery Co., Ltd..\n\nIt is an advanced wheel loader designed and developed through in-depth market analysis and technical research. Compared to earlier models, it delivers strong performance and a sleek design, along with significantly enhanced reliability, safety, comfort, and ease of maintenance.",
  "XC958": "The XC958 represents a newly released generation of equipment from XCMG Construction Machinery Co., Ltd..\n\nThis wheel loader has been engineered using detailed technical studies and thorough market insights. It combines strong operational efficiency with a modern, streamlined look, while also providing notable advancements in durability, safety, operator comfort, and maintenance convenience over previous models.",
  XE140I_K: "The XE140I_K Excavator is a high-performance machine built for demanding tasks such as crusher operations, wagon unloading, and irrigation projects. Powered by a 75/2200, this excavator combines robust power with fuel efficiency, ensuring consistent performance across a range of industrial and construction applications. With an operating weight of 13600 kg and a bucket capacity of  0.65 cubic meters, the XE140I_K excels in material handling, offering excellent lifting capacity and control. This makes it ideal for efficiently unloading heavy materials from wagons, feeding crushers, and managing large-scale irrigation infrastructure projects.",
  XE215I_K:
    "The XE215I_K Excavator is a heavy-duty machine built for tough environments like stone quarries and sand mining sites. Powered by a 174.7 hp Isuzu engine, it delivers strong digging performance and good fuel efficiency for demanding tasks.\n\nWith an operating weight of 22,900 kg and a bucket capacity of 0.9–1.2 cubic meters, it is designed for efficient material extraction and handling. Its powerful engine and hydraulic system enable it to handle hard materials like stone and sand with ease. Durable and reliable, the XE215I_K improves productivity while minimizing downtime in high-demand operations.",
  "XE230CLC": "The XE230C LC Excavator is a heavy-duty machine built for tough environments like stone quarries and sand mining sites. Powered by a 174.7 hp Isuzu engine, it delivers strong digging performance and good fuel efficiency for demanding tasks.\n\nWith an operating weight of 22,900 kg and a bucket capacity of 0.9–1.2 cubic meters, it is designed for efficient material extraction and handling. Its powerful engine and hydraulic system enable it to handle hard materials like stone and sand with ease.Durable and reliable, the XE230C LC improves productivity while minimizing downtime in high-demand operations.",
  "XE380C": "",
  "XP163": "The XP163 pneumatic tire roller is essential equipment for constructing high-grade highways, large-scale foundations, and various types of filling and compaction work. Its distinctive kneading and compaction capability make it difficult to replace with other machines.\n\nThe XP163 is a self-propelled static roller designed to deliver efficient and reliable compaction performance. It is suitable for compacting asphalt pavements, as well as base and sub-base layers and different types of fill materials. Due to its versatility and effectiveness, it is commonly used in major infrastructure projects such as roads, airports, ports, and dams, with particular importance in high-grade highway construction.",
  "ZL30E":
    "The XCMG machine is built with heavy-duty structural components for reliable performance in harsh working conditions. Advanced design and fatigue testing improve durability and stability, while the water treatment system helps maintain cleaner air quality during underground operations.\n\nThe adjustable cab shelter enhances adaptability to different site conditions, and optional attachments such as a larger bucket, extended boom, and side-dumping device provide greater flexibility for various applications.",
  "XTR4/260": `The XCMG XTR series roadheaders are advanced tunnel excavation machines designed to meet the demands of various tunnel cross-sections. These machines offer strong rock-cutting capability, high operational efficiency, and a wide cutting range, making them suitable for applications such as water conservancy tunnels, subway construction, and highway or railway tunneling projects.

The XTR4/260 roadheader is built with excellent geological adaptability, allowing it to perform effectively in different ground conditions, including rock with considerable hardness. It delivers stable cutting performance with reduced wear on the cutting head, ensuring durability and cost efficiency. The machine is capable of excavating a variety of tunnel shapes, including semicircular, oval, rectangular, and horseshoe sections, providing flexibility for different engineering requirements.`,
  "XTR6/280": `The XCMG XTR series roadheaders are advanced tunnel excavation machines developed to handle tunnels with a variety of cross-sectional shapes. They are known for their strong rock-breaking capacity, high operational efficiency, and wide cutting coverage, making them suitable for projects such as water conservancy works, metro systems, and highway or railway tunnel construction.

The XTR6/280 roadheader is designed with strong geological adaptability, allowing it to operate effectively in different rock conditions, including relatively hard formations. It ensures stable cutting performance with reduced wear on the cutting head, improving durability and cost efficiency. The machine can excavate various tunnel profiles, such as semicircular, oval, rectangular, and horseshoe shapes, offering flexibility for diverse construction requirements.`,
  "XTR7/360": `The XCMG XTR series roadheaders are modern tunnel excavation machines developed to meet the requirements of tunnels with different cross-sectional shapes. This series is known for its strong rock-cutting capability, high working efficiency, and broad cutting coverage, making it suitable for water conservancy projects, subway systems, and large-scale highway and railway tunnel construction.

The XTR7/360 roadheader offers excellent adaptability to varying geological conditions and can operate reliably in tunnels with high rock hardness. It delivers consistent cutting performance while minimizing wear on the cutting head, enhancing durability and reducing maintenance needs. Additionally, it supports excavation of multiple tunnel profiles, including semicircular, oval, rectangular, and horseshoe shapes, providing flexibility for complex engineering projects.`,
  "XUD135": `The machine is designed for high reliability, featuring a lightweight aluminum alloy boom that offers excellent resistance to bending, torsion, and fatigue. Its unique single-layer hose reel design helps extend hose lifespan while reducing maintenance effort.

It ensures precise operation with a telescopic drill boom that remains parallel in all directions, allowing for quick and accurate positioning. The square structural design enhances overall strength and provides effective shock absorption.

For stable performance, the drilling system is equipped with functions such as anti-jamming, prevention of idle drilling, and automatic withdrawal, which improve efficiency and minimize wear on drilling tools.

In terms of safety, the machine is fitted with a fully enclosed protective hood, offering secure and reliable protection during operation.`,
  "XTD275": `The XUD275 drill jumbo is engineered for high reliability, featuring a lightweight aluminum alloy boom that provides strong resistance to bending, torsion, and fatigue. Its specially designed single-layer hose reel helps extend hose service life while reducing maintenance requirements.

The machine delivers precise operation through its telescopic drill boom, which maintains parallel alignment in all directions for fast and accurate positioning. In addition, the square structural design enhances strength and ensures effective shock absorption during operation.

For consistent and stable performance, the drilling system includes functions such as anti-jamming, prevention of idle drilling, and automatic rod withdrawal, improving efficiency while reducing wear on drilling tools.

In terms of safety, the XUD275 is equipped with a fully enclosed protective hood, ensuring safe and reliable protection for operators throughout the working process.`,
  "XUD275": `The XUD275 drill jumbo is engineered for high reliability, featuring a lightweight aluminum alloy boom that provides strong resistance to bending, torsion, and fatigue. Its specially designed single-layer hose reel helps extend hose service life while reducing maintenance requirements.

The machine delivers precise operation through its telescopic drill boom, which maintains parallel alignment in all directions for fast and accurate positioning. In addition, the square structural design enhances strength and ensures effective shock absorption during operation.

For consistent and stable performance, the drilling system includes functions such as anti-jamming, prevention of idle drilling, and automatic rod withdrawal, improving efficiency while reducing wear on drilling tools.

In terms of safety, the XUD275 is equipped with a fully enclosed protective hood, ensuring safe and reliable protection for operators throughout the working process.`,
  "XTD295": `The XTD295 two-boom drill jumbo is primarily designed for tunneling construction, underground mining, and other subsurface engineering projects. It is suitable for drilling blasting holes, anchor bolt holes, and slot holes, making it highly versatile for underground operations.

The machine can also be equipped with an additional working platform, which facilitates the installation of explosives, anchor bolts, and other related equipment. With a maximum working coverage area of up to 90 m² or 104 m², it provides efficient and extensive drilling capability for large-scale underground projects.`,
  "XUD295": `The XTD295 two-boom drill jumbo is primarily designed for tunneling construction, underground mining, and other subsurface engineering projects. It is suitable for drilling blasting holes, anchor bolt holes, and slot holes, making it highly versatile for underground operations.

The machine can also be equipped with an additional working platform, which facilitates the installation of explosives, anchor bolts, and other related equipment. With a maximum working coverage area of up to 90 m² or 104 m², it provides efficient and extensive drilling capability for large-scale underground projects.`,
  SQS68TL_4: `The XCMG SQS68TL_4 truck-mounted crane is designed for efficient lifting operations with reliable performance and a durable boom structure. It offers strong lifting capability, smooth slewing, and stable operation, making it suitable for a wide range of construction and logistics lifting tasks.`,
  /** Excel workbook provides SQS68TL_4 copy; SQS68TL_5 sheet is empty. */
  SQS68TL_5: `The XCMG SQS68TL_4 truck-mounted crane is designed for efficient lifting operations with reliable performance and a durable boom structure. It offers strong lifting capability, smooth slewing, and stable operation, making it suitable for a wide range of construction and logistics lifting tasks.`,
  SQS125TL_4: `The XCMG SQS125TL_4 truck-mounted crane features a high-strength polygonal boom structure that provides strong lifting performance, fast lifting speed, and stable operation. It is designed for construction, logistics, and general lifting applications where reliability and efficiency are required.`,
  "SQS157ETL-4": `The XCMG SQS157ETL-4 truck-mounted crane is designed with a high-strength polygonal boom structure, providing strong lifting capacity, fast lifting speed, and stable performance. It is suitable for a range of lifting applications requiring reliable operation and durable construction.`,
  XCT25_Y1: `The XCT25_Y1 is a three-axle, 25-ton truck crane designed with an extended boom and enhanced lifting capability. It features a four-section boom structure and optimized chassis layout for stable operation, efficient performance, and convenient transport—well-suited for general lifting tasks on construction and infrastructure projects.`,
  XCT25L4_Y: `The XCT25L4_Y truck crane is widely used in logistics, warehousing, construction sites, and various other industrial applications. Its reliable performance and versatile design make it suitable for efficient lifting and material handling operations in different working environments. In Nepal, UHEEM supports this model as part of the authorized XCMG range with sales, genuine parts, and after-sales service.`,
  XCT50_Y1: `The XCT50_Y1 truck crane is widely used for lifting operations in a variety of general engineering projects. It is well-suited for construction sites, bridges, urban infrastructure, and industrial lifting tasks, offering reliable performance and strong adaptability to different work conditions.`,
  XCT60_Y1: `The XCT60_Y1 truck crane is widely used for lifting operations in a variety of general engineering projects. It is well-suited for construction sites, bridges, urban infrastructure, and industrial lifting tasks, offering reliable performance and strong adaptability to different work conditions.`,
  XCT80_Y1: `The XCT80_Y1 truck crane is extensively used for lifting operations in a wide range of general engineering projects. It is suitable for a variety of construction and infrastructure applications, delivering stable performance, strong lifting capability, and dependable operation.`,
  XCT110_Y2: `The 4-axle 110-ton truck crane is designed to deliver powerful lifting performance along with precise and responsive control. Its robust chassis, optimized boom system, and stable lifting configuration make it suitable for heavy-duty lifting tasks across infrastructure, industrial, and general engineering projects.`,
  XCT110_Y: `The XCT110_Y truck crane is a four-axle, 110-ton lifting machine designed to deliver strong performance along with precise and responsive control. It is built for heavy-duty lifting operations across infrastructure and general engineering projects, balancing lifting capability with transport convenience.`,
  XCT110_Y1: `The XCT110_Y truck crane is a four-axle, 110-ton lifting machine designed to deliver strong performance along with precise and responsive control. It is built for heavy-duty lifting operations across infrastructure and general engineering projects, balancing lifting capability with transport convenience.`,
  "XR138E": `The XR138E is a compact rotary drilling rig designed for efficient and stable foundation construction. It features a fuel-efficient engine, advanced hydraulic system, and reliable drilling performance for a variety of working conditions.

With its intelligent control technology, durable structure, and easy operation, the machine delivers improved efficiency, smooth performance, and dependable results for different construction projects.`,
  "XR130E": `The XR130E is a compact rotary drilling rig designed for efficient and stable foundation construction. It features a fuel-efficient engine, reliable hydraulic system, and adaptable drilling capabilities, making it suitable for urban construction, bridge works, and medium-depth drilling projects.`,
  "XR158E": `The XR158E is a compact and efficient rotary drilling rig designed for foundation construction projects. It is equipped with a fuel-efficient engine, reliable hydraulic system, and stable drilling performance, allowing it to handle diverse construction conditions with high productivity.`,
  "XR178E": `The XR178E is a versatile rotary drilling rig designed to efficiently handle different construction requirements. Its adaptable design allows it to perform a wide range of pile foundation operations, making it suitable for infrastructure, urban development, and general foundation engineering projects.`,
  "XR210I": `The XR210I is a high-performance rotary drilling rig designed for efficient and stable foundation construction. It features a powerful and fuel-efficient engine, advanced hydraulic control, and reliable drilling capability for a wide range of pile foundation projects.`,
  "XR218E": `The XR218E is a versatile rotary drilling rig designed for efficient and reliable foundation construction. It features a turbocharged engine, strong rotary torque, and stable chassis performance, making it suitable for complex drilling applications in infrastructure and civil engineering works.`,
  "XR240E": `The XR240E is a multifunctional rotary drilling rig designed for flexible and efficient construction operations. It features quick switching between drilling methods, high torque output, and stable operation, making it suitable for large foundation projects and demanding site conditions.`,
};

/** Normalize model codes for lookup (matches EV helper behaviour). */
const roadEarthModelAliases: Record<string, string> = {
  XR210C: "XR210I",
};

export function roadEarthSpecModelKey(model: string): string {
  const normalized = model.replace(/\s+/g, "").replace(/-/g, "_").toUpperCase();
  return roadEarthModelAliases[normalized] ?? normalized;
}

export function roadEarthSpecificationsForModel(model: string): SpecRow[] {
  const key = roadEarthSpecModelKey(model);
  return roadEarthSpecificationsByModel[key] ?? [];
}

export function roadEarthDescriptionForModel(model: string): string | undefined {
  const key = roadEarthSpecModelKey(model);
  const d = roadEarthDescriptionsByModel[key];
  return d && d.trim() !== "" ? d : undefined;
}
